import {
  MedicalOfficerProfile,
  MedicalRequest,
  MedicalAppointment,
  MedicalVisitRecord,
  MedicalLeaveRecord,
  MedicineInventoryItem,
  AmbulanceReferralRecord,
  MedicalReportItem,
  PharmacistProfile,
  StudentMedicineDispenseRecord,
  EmergencyVehicleFleet,
} from './types';

export const INITIAL_MEDICAL_OFFICER: MedicalOfficerProfile = {
  name: 'Dr. Pratima Mishra, MD',
  badgeId: 'DOC-MED-012',
  designation: 'Campus Chief Medical Officer & Clinic In-Charge',
  qualifications: 'MBBS, MD (General Medicine) - SCB Medical College',
  department: 'University Health & Wellness Center',
  phone: '+91 94370 88219',
  ambulanceHelpline: '+91 94370 00108',
  shift: 'OPD Consultation (09:00 AM - 05:00 PM) • 24x7 Emergency On-Call',
  clinicBay: 'Campus Health Center Bay 1 (Emergency & Minor OT)',
  avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=160',
};

export const INITIAL_MEDICAL_REQUESTS: MedicalRequest[] = [
  {
    id: 'med-req-01',
    ticketNumber: 'MR-2026-108',
    studentName: 'Aman Verma',
    studentId: 'CS2023089',
    studentRoll: 'REC-2023-CS089',
    studentPhone: '+91 98610 99881',
    parentPhone: '+91 94371 44520',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-102',
    requestType: 'Doctor Consultation',
    description: 'High fever (102°F), body chills, sore throat, and severe fatigue since last night.',
    urgency: 'HIGH',
    vitals: { bp: '118/76', temp: '102.1°F', spo2: '98%', pulse: '88 bpm' },
    dateTime: 'Today, 09:30 AM',
    status: 'In Progress',
    attendingStaff: 'Dr. Pratima Mishra, MD',
    prescription: 'Tab Paracetamol 650mg TDS, Tab Cetirizine 10mg HS, Warm saline gargles',
    doctorNotes: 'Acute febrile illness. Prescribed antipyretics. 3 days hostel bed rest advised.',
    medicalLeaveRecommended: true,
    medicalLeaveDays: 3,
  },
  {
    id: 'med-req-02',
    ticketNumber: 'MR-2026-105',
    studentName: 'Subham Pradhan',
    studentId: 'CS2023042',
    studentRoll: 'REC-2023-CS042',
    studentPhone: '+91 98765 43210',
    parentPhone: '+91 94370 88990',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-204',
    requestType: 'Nurse / First Aid',
    description: 'Minor superficial abrasion on right forearm sustained during basketball practice.',
    urgency: 'LOW',
    vitals: { bp: '120/80', temp: '98.4°F', spo2: '99%', pulse: '74 bpm' },
    dateTime: 'Today, 08:45 AM',
    status: 'Completed',
    attendingStaff: 'Nurse Snehalata Sahoo',
    prescription: 'Betadine antiseptic dressing, Soframycin ointment applied',
    doctorNotes: 'Wound cleaned with saline, aseptic dressing applied. No suture required.',
  },
  {
    id: 'med-req-03',
    ticketNumber: 'MR-2026-112',
    studentName: 'Rohan Jena',
    studentId: 'EE2022031',
    studentRoll: 'REC-2022-EE031',
    studentPhone: '+91 98532 11009',
    parentPhone: '+91 94371 55667',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-301',
    requestType: 'Doctor Consultation',
    description: 'Recurrent migraine headache with nausea and sensitivity to light during screen work.',
    urgency: 'MEDIUM',
    vitals: { bp: '124/82', temp: '98.6°F', spo2: '99%', pulse: '78 bpm' },
    dateTime: 'Today, 10:15 AM',
    status: 'Accepted',
    attendingStaff: 'Dr. Pratima Mishra, MD',
    prescription: 'Tab Naproxen 250mg SOS, Tab Domperidone 10mg SOS, Screen blue light restriction',
  },
  {
    id: 'med-req-04',
    ticketNumber: 'MR-2026-119',
    studentName: 'Mithun Sahoo',
    studentId: 'CS2023015',
    studentRoll: 'REC-2023-CS015',
    studentPhone: '+91 98765 88991',
    parentPhone: '+91 94370 88990',
    hostel: 'Nilgiri Residence (Block B)',
    room: 'B-205',
    requestType: 'Medical Leave',
    description: 'Viral gastroenteritis recuperation follow-up and fitness clearance.',
    urgency: 'LOW',
    vitals: { bp: '116/74', temp: '98.2°F', spo2: '99%', pulse: '72 bpm' },
    dateTime: 'Today, 08:00 AM',
    status: 'New',
  },
  {
    id: 'med-req-05',
    ticketNumber: 'MR-2026-124',
    studentName: 'Pritam Mohanty',
    studentId: 'CS2023044',
    studentRoll: 'REC-2023-CS044',
    studentPhone: '+91 98765 11223',
    parentPhone: '+91 94370 77102',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-210',
    requestType: 'Emergency',
    description: 'Acute sharp abdominal pain in right iliac fossa with vomiting. Suspected acute appendicitis.',
    urgency: 'EMERGENCY',
    vitals: { bp: '138/88', temp: '100.2°F', spo2: '97%', pulse: '104 bpm' },
    dateTime: 'Today, 07:15 AM',
    status: 'Completed',
    attendingStaff: 'Dr. Pratima Mishra, MD',
    doctorNotes: 'Tender McBurney point. Referred to AIIMS Bhubaneswar surgical emergency via 24x7 campus ambulance.',
  },
];

export const INITIAL_APPOINTMENTS: MedicalAppointment[] = [
  {
    id: 'apt-01',
    appointmentNumber: 'APT-2026-089',
    studentName: 'Aman Verma',
    studentRoll: 'REC-2023-CS089',
    hostel: 'Nilgiri Block A',
    room: 'A-102',
    phone: '+91 98610 99881',
    doctorName: 'Dr. Pratima Mishra, MD',
    specialty: 'General Medicine & Triage',
    slotTime: '10:30 AM',
    slotDate: 'Today',
    status: 'IN_CONSULTATION',
    symptoms: 'High fever & acute pharyngitis review',
  },
  {
    id: 'apt-02',
    appointmentNumber: 'APT-2026-092',
    studentName: 'Rohan Jena',
    studentRoll: 'REC-2022-EE031',
    hostel: 'Nilgiri Block A',
    room: 'A-301',
    phone: '+91 98532 11009',
    doctorName: 'Dr. Pratima Mishra, MD',
    specialty: 'General Medicine',
    slotTime: '11:15 AM',
    slotDate: 'Today',
    status: 'WAITING',
    symptoms: 'Severe tension headache & photophobia',
  },
  {
    id: 'apt-03',
    appointmentNumber: 'APT-2026-095',
    studentName: 'Subham Pradhan',
    studentRoll: 'REC-2023-CS042',
    hostel: 'Nilgiri Block A',
    room: 'A-204',
    phone: '+91 98765 43210',
    doctorName: 'Dr. K. C. Mohanty (Consultant Ortho)',
    specialty: 'Sports Injuries & Orthopaedics',
    slotTime: '03:00 PM',
    slotDate: 'Today',
    status: 'SCHEDULED',
    symptoms: 'Follow-up wrist tendon strain examination',
  },
  {
    id: 'apt-04',
    appointmentNumber: 'APT-2026-098',
    studentName: 'Debashis Rout',
    studentRoll: 'REC-2023-CS088',
    hostel: 'Nilgiri Block A',
    room: 'A-101',
    phone: '+91 94371 99221',
    doctorName: 'Dr. Pratima Mishra, MD',
    specialty: 'General Medicine',
    slotTime: '04:00 PM',
    slotDate: 'Today',
    status: 'SCHEDULED',
    symptoms: 'Allergic rhinitis & seasonal pollen sneezing',
  },
];

export const INITIAL_MEDICAL_VISITS: MedicalVisitRecord[] = [
  {
    id: 'vis-med-01',
    visitNumber: 'OPD-2026-4412',
    studentName: 'Subham Pradhan',
    studentRoll: 'REC-2023-CS042',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-204',
    visitDate: 'Today',
    visitTime: '08:45 AM',
    diagnosis: 'Knee wound and scratches from sports ground',
    treatment: 'Cleaned wound with Betadine, applied ointment, and put bandage.',
    prescribedMedicines: ['Tab Paracetamol 500mg SOS', 'Soframycin Skin Cream 30g'],
    followUpDate: 'In 3 days for dressing check',
    attendingDoctor: 'Dr. Pratima Mishra, MD',
  },
  {
    id: 'vis-med-02',
    visitNumber: 'OPD-2026-4398',
    studentName: 'Aman Verma',
    studentRoll: 'REC-2023-CS089',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-102',
    visitDate: 'Today',
    visitTime: '09:30 AM',
    diagnosis: 'High fever and sore throat',
    treatment: 'Gave fever medicine (Paracetamol), allergy tablet, and advised plenty of water.',
    prescribedMedicines: ['Tab Dolo 650mg TDS x 3d', 'Tab Levocetirizine 5mg HS x 5d', 'Betadine Gargle 100ml'],
    followUpDate: '09 Oct 2026',
    attendingDoctor: 'Dr. Pratima Mishra, MD',
  },
  {
    id: 'vis-med-03',
    visitNumber: 'OPD-2026-4380',
    studentName: 'Mithun Sahoo',
    studentRoll: 'REC-2023-CS015',
    hostel: 'Nilgiri Residence (Block B)',
    room: 'B-205',
    visitDate: 'Yesterday',
    visitTime: '04:15 PM',
    diagnosis: 'Stomach ache, loose motion, and dehydration',
    treatment: 'Gave ORS electrolyte water and stomach pain relief tablets.',
    prescribedMedicines: ['Electral ORS 4.2g x 5 sachets', 'Cap Econorm 250mg BD x 3d', 'Tab Drotikind 40mg SOS'],
    attendingDoctor: 'Dr. Pratima Mishra, MD',
  },
];

export const INITIAL_MEDICAL_LEAVES: MedicalLeaveRecord[] = [
  {
    id: 'ml-01',
    leaveNumber: 'MED-LV-2026-042',
    studentName: 'Aman Verma',
    studentRoll: 'REC-2023-CS089',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-102',
    startDate: '06 Oct 2026',
    endDate: '08 Oct 2026',
    days: 3,
    operationalReason: 'Acute viral febrile illness — 3 days hostel room recuperation advised by CMO.',
    medicalStatus: 'APPROVED_BY_WARDEN',
    recommendedBy: 'Dr. Pratima Mishra, MD',
    wardenNotified: true,
    isFitToResume: false,
  },
  {
    id: 'ml-02',
    leaveNumber: 'MED-LV-2026-039',
    studentName: 'Pritam Mohanty',
    studentRoll: 'REC-2023-CS044',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-210',
    startDate: '06 Oct 2026',
    endDate: '12 Oct 2026',
    days: 7,
    operationalReason: 'Surgical referral recuperation (Hospitalized at AIIMS). Extended hostel leave required.',
    medicalStatus: 'RECOMMENDED',
    recommendedBy: 'Dr. Pratima Mishra, MD',
    wardenNotified: true,
    isFitToResume: false,
  },
  {
    id: 'ml-03',
    leaveNumber: 'MED-LV-2026-035',
    studentName: 'Mithun Sahoo',
    studentRoll: 'REC-2023-CS015',
    hostel: 'Nilgiri Residence (Block B)',
    room: 'B-205',
    startDate: '03 Oct 2026',
    endDate: '05 Oct 2026',
    days: 2,
    operationalReason: 'Acute gastroenteritis bed rest — complete recovery verified.',
    medicalStatus: 'EXPIRED',
    recommendedBy: 'Dr. Pratima Mishra, MD',
    wardenNotified: true,
    isFitToResume: true,
  },
];

export const INITIAL_PHARMACIST_PROFILE: PharmacistProfile = {
  name: 'Mr. Abinash Mohanty',
  registrationNumber: 'Reg No: OR-5821',
  qualifications: 'Campus Pharmacist',
  phone: '+91 98610 03305',
  timings: '08:00 AM – 09:30 PM (Daily)',
  location: 'Ground Floor, Health Unit 5 (Near Hostel A)',
  dutyStatus: 'ON_DUTY',
};

export const INITIAL_EMERGENCY_VEHICLE_FLEET: EmergencyVehicleFleet = {
  vehicleNumber: 'OD-02-AX-108 (Campus 24×7 Ambulance)',
  vehicleType: 'Campus Emergency Van',
  driverName: 'Kailash Nayak',
  driverPhone: '+91 94370 00108',
  standbyPost: 'Main Gate #1 Turnstile Security Post',
  status: 'STANDBY_READY',
  nearestHospitals: [
    {
      name: 'KIMS Hospital',
      distance: '4.5 km',
      etaMinutes: 12,
      phone: '+91 674 272 5228',
    },
    {
      name: 'Hi-Tech Hospital',
      distance: '7.2 km',
      etaMinutes: 18,
      phone: '+91 674 237 1406',
    },
    {
      name: 'AIIMS Hospital Emergency',
      distance: '14.0 km',
      etaMinutes: 28,
      phone: '108 / +91 674 247 6789',
    },
  ],
};

export const INITIAL_STUDENT_DISPENSATIONS: StudentMedicineDispenseRecord[] = [
  {
    id: 'disp-01',
    dispenseNumber: 'DISP-2026-104',
    studentName: 'Subham Pradhan',
    studentRoll: 'REC-2023-CS042',
    hostelRoom: 'Nilgiri A-204',
    medicineName: 'WHO Formulation Oral Rehydration Salts (Electral)',
    quantity: 2,
    unit: 'Sachets',
    dispensedTime: 'Today, 08:45 AM',
    pharmacistName: 'Mr. Abinash Mohanty',
    directions: 'Dissolve 1 sachet in 1 liter clean drinking water; sip frequently.',
    isFreeStudentQuota: true,
  },
  {
    id: 'disp-02',
    dispenseNumber: 'DISP-2026-103',
    studentName: 'Aman Verma',
    studentRoll: 'REC-2023-CS089',
    hostelRoom: 'Nilgiri A-102',
    medicineName: 'Paracetamol 650mg (Dolo 650)',
    quantity: 1,
    unit: 'Strip (10 Tabs)',
    dispensedTime: 'Today, 09:35 AM',
    pharmacistName: 'Mr. Abinash Mohanty',
    directions: 'Take 1 tablet after food if body temperature rises above 99.5°F.',
    isFreeStudentQuota: true,
  },
  {
    id: 'disp-03',
    dispenseNumber: 'DISP-2026-102',
    studentName: 'Ananya Pattnaik',
    studentRoll: 'REC-2023-EC018',
    hostelRoom: 'Shivalik B-312',
    medicineName: 'Cetirizine HCl 10mg (Alen OD)',
    quantity: 1,
    unit: 'Strip (10 Tabs)',
    dispensedTime: 'Today, 09:10 AM',
    pharmacistName: 'Mr. Abinash Mohanty',
    directions: 'Take 1 tablet at night for allergic cold and sneezing.',
    isFreeStudentQuota: true,
  },
  {
    id: 'disp-04',
    dispenseNumber: 'DISP-2026-101',
    studentName: 'Rohan Jena',
    studentRoll: 'REC-2022-EE031',
    hostelRoom: 'Nilgiri A-301',
    medicineName: 'Volini Pain Relief Spray & Gel',
    quantity: 1,
    unit: 'Tube (50g)',
    dispensedTime: 'Yesterday, 06:15 PM',
    pharmacistName: 'Mr. Abinash Mohanty',
    directions: 'Gently apply on right ankle joint; avoid vigorous massage.',
    isFreeStudentQuota: true,
  },
];

export const INITIAL_MEDICINE_INVENTORY: MedicineInventoryItem[] = [
  {
    id: 'med-inv-01',
    code: 'MED-DOLO-650',
    name: 'Paracetamol 650mg (Dolo 650)',
    category: 'Antipyretic',
    dosage: '650mg Tab',
    quantity: 140,
    unit: 'Strips',
    minStock: 50,
    expiryDate: '12/2027',
    isLowStock: false,
    isExpiringSoon: false,
    location: 'Pharmacy Counter Shelf A-1',
    isOtcStudentEssential: true,
    indication: 'Fever, headache & body aches relief',
  },
  {
    id: 'med-inv-02',
    code: 'MED-ORS-ELC',
    name: 'ORS Electrolyte Packs (Electral)',
    category: 'Electrolyte',
    dosage: '21.8g Sachet',
    quantity: 12,
    unit: 'Sachets',
    minStock: 40,
    expiryDate: '04/2027',
    isLowStock: true,
    isExpiringSoon: false,
    location: 'Pharmacy Counter Shelf A-2',
    isOtcStudentEssential: true,
    indication: 'Dehydration, sunstroke & gastroenteritis',
  },
  {
    id: 'med-inv-03',
    code: 'MED-CET-10',
    name: 'Cetirizine 10mg (Alen OD)',
    category: 'Antihistamine',
    dosage: '10mg Tab',
    quantity: 85,
    unit: 'Strips',
    minStock: 30,
    expiryDate: '08/2027',
    isLowStock: false,
    isExpiringSoon: false,
    location: 'Pharmacy Counter Shelf A-3',
    isOtcStudentEssential: true,
    indication: 'Allergy, common cold & sneezing',
  },
  {
    id: 'med-inv-04',
    code: 'MED-DIG-TAB',
    name: 'Antacid Gel / Chewable Tablets (Digene)',
    category: 'Antacid',
    dosage: 'Chewable Tabs / Syrup',
    quantity: 60,
    unit: 'Strips',
    minStock: 25,
    expiryDate: '10/2027',
    isLowStock: false,
    isExpiringSoon: false,
    location: 'Pharmacy Counter Shelf B-1',
    isOtcStudentEssential: true,
    indication: 'Acidity, heartburn & stomach indigestion',
  },
  {
    id: 'med-inv-05',
    code: 'MED-BET-100',
    name: 'Burnol & Betadine Antiseptic Solution',
    category: 'First Aid',
    dosage: '100ml Bottle / 20g Tube',
    quantity: 6,
    unit: 'Bottles',
    minStock: 15,
    expiryDate: '11/2026',
    isLowStock: true,
    isExpiringSoon: true,
    location: 'First Aid Dressing Bay',
    isOtcStudentEssential: true,
    indication: 'Minor cuts, scrapes & minor burns antiseptic',
  },
  {
    id: 'med-inv-06',
    code: 'MED-COT-GAU',
    name: 'Sterile Cotton Rolls & Bandages',
    category: 'First Aid',
    dosage: 'Sterile 5cm x 3m Rolls',
    quantity: 35,
    unit: 'Rolls',
    minStock: 20,
    expiryDate: '01/2029',
    isLowStock: false,
    isExpiringSoon: false,
    location: 'First Aid Dressing Bay',
    isOtcStudentEssential: true,
    indication: 'Wound dressing, gauze & fracture immobilization',
  },
  {
    id: 'med-inv-07',
    code: 'MED-VOL-50',
    name: 'Volini Pain Relief Spray & Gel',
    category: 'Ointment',
    dosage: '50g Tube / 55g Spray',
    quantity: 22,
    unit: 'Tubes',
    minStock: 20,
    expiryDate: '06/2027',
    isLowStock: false,
    isExpiringSoon: false,
    location: 'Pharmacy Counter Shelf B-2',
    isOtcStudentEssential: true,
    indication: 'Sports sprain, muscle ache & neck stiffness',
  },
  {
    id: 'med-inv-08',
    code: 'MED-SAL-INH',
    name: 'Salbutamol Inhaler (SOS)',
    category: 'Respiratory',
    dosage: '100mcg MDI Inhaler',
    quantity: 8,
    unit: 'Canisters',
    minStock: 5,
    expiryDate: '09/2027',
    isLowStock: false,
    isExpiringSoon: false,
    location: 'Emergency Resuscitation Tray',
    isOtcStudentEssential: true,
    indication: 'Emergency asthma bronchospasm & wheezing',
  },
  {
    id: 'med-inv-09',
    code: 'MED-DIG-THM',
    name: 'Digital Clinical Thermometers',
    category: 'Equipment',
    dosage: 'Fast 10s Digital Probe',
    quantity: 10,
    unit: 'Units',
    minStock: 5,
    expiryDate: 'N/A (Calibrated)',
    isLowStock: false,
    isExpiringSoon: false,
    location: 'Vitals Triage Station',
    isOtcStudentEssential: true,
    indication: 'Body temperature monitoring at counter',
  },
  {
    id: 'med-inv-10',
    code: 'MED-BPM-MON',
    name: 'Automatic Blood Pressure Monitor',
    category: 'Equipment',
    dosage: 'Digital Arm Cuff (Omron)',
    quantity: 4,
    unit: 'Units',
    minStock: 3,
    expiryDate: 'N/A (Calibrated)',
    isLowStock: false,
    isExpiringSoon: false,
    location: 'Vitals Triage Station',
    isOtcStudentEssential: true,
    indication: 'Vitals blood pressure & pulse check counter',
  },
  {
    id: 'med-inv-11',
    code: 'MED-AZI-500',
    name: 'Azithromycin (Azee 500mg)',
    category: 'Antibiotic',
    dosage: '500mg Tab',
    quantity: 45,
    unit: 'Strips',
    minStock: 25,
    expiryDate: '03/2028',
    isLowStock: false,
    isExpiringSoon: false,
    location: 'Locked Schedule H Safe',
    isOtcStudentEssential: false,
    indication: 'Prescription bacterial respiratory infections',
  },
];

export const INITIAL_AMBULANCE_REFERRALS: AmbulanceReferralRecord[] = [
  {
    id: 'amb-ref-01',
    referralNumber: 'REF-2026-018',
    studentName: 'Pritam Mohanty',
    studentRoll: 'REC-2023-CS044',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-210',
    dispatchTime: 'Today, 07:40 AM',
    vehicleNumber: 'OD-02-AMB-108 (Campus 24x7 Ambulance)',
    driverName: 'Kailash Nayak',
    driverPhone: '+91 94370 00108',
    destinationHospital: 'AIIMS Hospital Emergency',
    referralReason: 'Acute abdominal emergency (Suspected appendicitis / peritonitis)',
    accompanyingStaff: 'Male Nurse Ranjan Jena',
    emergencyContactCalled: true,
    status: 'ADMITTED',
  },
  {
    id: 'amb-ref-02',
    referralNumber: 'REF-2026-014',
    studentName: 'Debashis Rout',
    studentRoll: 'REC-2023-CS088',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-101',
    dispatchTime: '01 Oct 2026, 02:15 PM',
    vehicleNumber: 'OD-02-AMB-108',
    driverName: 'Kailash Nayak',
    driverPhone: '+91 94370 00108',
    destinationHospital: 'Capital Hospital (Trauma Care)',
    referralReason: 'Sports ankle ligament rupture requiring X-ray imaging and plaster cast',
    accompanyingStaff: 'Warden Representative B. Swain',
    emergencyContactCalled: true,
    status: 'COMPLETED',
  },
];

export const INITIAL_MEDICAL_REPORTS: MedicalReportItem[] = [
  {
    id: 'rep-med-01',
    name: 'Daily OPD Footfall & Clinical Consultation Summary',
    category: 'OPD_CONSULTATION',
    recordCount: 42,
    description: 'Patient registrations, vitals recorded, fever screenings, and prescriptions dispensed.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-med-02',
    name: 'Campus Emergency SOS Response & Ambulance Log',
    category: 'EMERGENCY_AMBULANCE',
    recordCount: 8,
    description: 'Distress triggers, ambulance dispatch turnaround minutes, and hospital referrals.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-med-03',
    name: 'Medical Leave Recommendations & Hostel Notifications',
    category: 'MEDICAL_LEAVE',
    recordCount: 16,
    description: 'Warden-cleared recuperation rest periods, communicable disease tracking, and resumption fitness.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-med-04',
    name: 'Pharmacy Consumption & Essential Medicine Stock Audit',
    category: 'PHARMACY',
    recordCount: 55,
    description: 'Analgesics, antibiotics, ORS sachets, expiry date watch-list, and purchase requisitions.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-med-05',
    name: 'Hostel Illness Epidemiology & Fever Cluster Surveillance',
    category: 'EPIDEMIOLOGY',
    recordCount: 24,
    description: 'Hostel block wise breakdown of viral fevers, seasonal allergies, and gastro complaints.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-med-06',
    name: 'Annual Student Health Screening & Physical Fitness Register',
    category: 'HEALTH_CHECKUP',
    recordCount: 120,
    description: 'Blood pressure baselines, BMI indices, vision tests, and chronic allergy registries.',
    generatedDate: 'Today',
    format: 'CSV',
  },
];
