import {
  MedicalOfficerProfile,
  MedicalRequest,
  MedicalAppointment,
  MedicalVisitRecord,
  MedicalLeaveRecord,
  MedicineInventoryItem,
  AmbulanceReferralRecord,
  MedicalReportItem,
} from './types';

export const INITIAL_MEDICAL_OFFICER: MedicalOfficerProfile = {
  name: 'Dr. Pratima Mishra, MD',
  badgeId: 'DOC-MED-012',
  designation: 'Campus Chief Medical Officer & Clinic In-Charge',
  qualifications: 'MBBS, MD (General Medicine) - SCB Medical College',
  department: 'University Health & Wellness Center',
  phone: '+91 94370 88219',
  ambulanceHelpline: '+91 94370 00108',
  shift: 'OPD Consultation (09:00 AM - 05:00 PM) • 24x7 Emergency On-Call',
  clinicBay: 'Campus Health Center Bay 1 (Emergency & Minor OT)',
  avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=160',
};

export const INITIAL_MEDICAL_REQUESTS: MedicalRequest[] = [
  {
    id: 'med-req-01',
    ticketNumber: 'MR-2026-108',
    studentName: 'Aman Verma',
    studentId: 'CS2023089',
    studentRoll: 'REC-2023-CS089',
    studentPhone: '+91 98610 99881',
    parentPhone: '+91 94371 44520',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-102',
    requestType: 'Doctor Consultation',
    description: 'High fever (102°F), body chills, sore throat, and severe fatigue since last night.',
    urgency: 'HIGH',
    vitals: { bp: '118/76', temp: '102.1°F', spo2: '98%', pulse: '88 bpm' },
    dateTime: 'Today, 09:30 AM',
    status: 'In Progress',
    attendingStaff: 'Dr. Pratima Mishra, MD',
    prescription: 'Tab Paracetamol 650mg TDS, Tab Cetirizine 10mg HS, Warm saline gargles',
    doctorNotes: 'Acute febrile illness. Prescribed antipyretics. 3 days hostel bed rest advised.',
    medicalLeaveRecommended: true,
    medicalLeaveDays: 3,
  },
  {
    id: 'med-req-02',
    ticketNumber: 'MR-2026-105',
    studentName: 'Subham Pradhan',
    studentId: 'CS2023042',
    studentRoll: 'REC-2023-CS042',
    studentPhone: '+91 98765 43210',
    parentPhone: '+91 94370 88990',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-204',
    requestType: 'Nurse / First Aid',
    description: 'Minor superficial abrasion on right forearm sustained during basketball practice.',
    urgency: 'LOW',
    vitals: { bp: '120/80', temp: '98.4°F', spo2: '99%', pulse: '74 bpm' },
    dateTime: 'Today, 08:45 AM',
    status: 'Completed',
    attendingStaff: 'Nurse Snehalata Sahoo',
    prescription: 'Betadine antiseptic dressing, Soframycin ointment applied',
    doctorNotes: 'Wound cleaned with saline, aseptic dressing applied. No suture required.',
  },
  {
    id: 'med-req-03',
    ticketNumber: 'MR-2026-112',
    studentName: 'Rohan Jena',
    studentId: 'EE2022031',
    studentRoll: 'REC-2022-EE031',
    studentPhone: '+91 98532 11009',
    parentPhone: '+91 94371 55667',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-301',
    requestType: 'Doctor Consultation',
    description: 'Recurrent migraine headache with nausea and sensitivity to light during screen work.',
    urgency: 'MEDIUM',
    vitals: { bp: '124/82', temp: '98.6°F', spo2: '99%', pulse: '78 bpm' },
    dateTime: 'Today, 10:15 AM',
    status: 'Accepted',
    attendingStaff: 'Dr. Pratima Mishra, MD',
    prescription: 'Tab Naproxen 250mg SOS, Tab Domperidone 10mg SOS, Screen blue light restriction',
  },
  {
    id: 'med-req-04',
    ticketNumber: 'MR-2026-119',
    studentName: 'Mithun Sahoo',
    studentId: 'CS2023015',
    studentRoll: 'REC-2023-CS015',
    studentPhone: '+91 98765 88991',
    parentPhone: '+91 94370 88990',
    hostel: 'Nilgiri Residence (Block B)',
    room: 'B-205',
    requestType: 'Medical Leave',
    description: 'Viral gastroenteritis recuperation follow-up and fitness clearance.',
    urgency: 'LOW',
    vitals: { bp: '116/74', temp: '98.2°F', spo2: '99%', pulse: '72 bpm' },
    dateTime: 'Today, 08:00 AM',
    status: 'New',
  },
  {
    id: 'med-req-05',
    ticketNumber: 'MR-2026-124',
    studentName: 'Pritam Mohanty',
    studentId: 'CS2023044',
    studentRoll: 'REC-2023-CS044',
    studentPhone: '+91 98765 11223',
    parentPhone: '+91 94370 77102',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-210',
    requestType: 'Emergency',
    description: 'Acute sharp abdominal pain in right iliac fossa with vomiting. Suspected acute appendicitis.',
    urgency: 'EMERGENCY',
    vitals: { bp: '138/88', temp: '100.2°F', spo2: '97%', pulse: '104 bpm' },
    dateTime: 'Today, 07:15 AM',
    status: 'Completed',
    attendingStaff: 'Dr. Pratima Mishra, MD',
    doctorNotes: 'Tender McBurney point. Referred to AIIMS Bhubaneswar surgical emergency via 24x7 campus ambulance.',
  },
];

export const INITIAL_APPOINTMENTS: MedicalAppointment[] = [
  {
    id: 'apt-01',
    appointmentNumber: 'APT-2026-089',
    studentName: 'Aman Verma',
    studentRoll: 'REC-2023-CS089',
    hostel: 'Nilgiri Block A',
    room: 'A-102',
    phone: '+91 98610 99881',
    doctorName: 'Dr. Pratima Mishra, MD',
    specialty: 'General Medicine & Triage',
    slotTime: '10:30 AM',
    slotDate: 'Today',
    status: 'IN_CONSULTATION',
    symptoms: 'High fever & acute pharyngitis review',
  },
  {
    id: 'apt-02',
    appointmentNumber: 'APT-2026-092',
    studentName: 'Rohan Jena',
    studentRoll: 'REC-2022-EE031',
    hostel: 'Nilgiri Block A',
    room: 'A-301',
    phone: '+91 98532 11009',
    doctorName: 'Dr. Pratima Mishra, MD',
    specialty: 'General Medicine',
    slotTime: '11:15 AM',
    slotDate: 'Today',
    status: 'WAITING',
    symptoms: 'Severe tension headache & photophobia',
  },
  {
    id: 'apt-03',
    appointmentNumber: 'APT-2026-095',
    studentName: 'Subham Pradhan',
    studentRoll: 'REC-2023-CS042',
    hostel: 'Nilgiri Block A',
    room: 'A-204',
    phone: '+91 98765 43210',
    doctorName: 'Dr. K. C. Mohanty (Consultant Ortho)',
    specialty: 'Sports Injuries & Orthopaedics',
    slotTime: '03:00 PM',
    slotDate: 'Today',
    status: 'SCHEDULED',
    symptoms: 'Follow-up wrist tendon strain examination',
  },
  {
    id: 'apt-04',
    appointmentNumber: 'APT-2026-098',
    studentName: 'Debashis Rout',
    studentRoll: 'REC-2023-CS088',
    hostel: 'Nilgiri Block A',
    room: 'A-101',
    phone: '+91 94371 99221',
    doctorName: 'Dr. Pratima Mishra, MD',
    specialty: 'General Medicine',
    slotTime: '04:00 PM',
    slotDate: 'Today',
    status: 'SCHEDULED',
    symptoms: 'Allergic rhinitis & seasonal pollen sneezing',
  },
];

export const INITIAL_MEDICAL_VISITS: MedicalVisitRecord[] = [
  {
    id: 'vis-med-01',
    visitNumber: 'OPD-2026-4412',
    studentName: 'Subham Pradhan',
    studentRoll: 'REC-2023-CS042',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-204',
    visitDate: 'Today',
    visitTime: '08:45 AM',
    diagnosis: 'Superficial skin abrasion (Sports injury)',
    treatment: 'Povidone-iodine cleansing, Soframycin topical ointment, protective dressing.',
    prescribedMedicines: ['Tab Paracetamol 500mg SOS', 'Soframycin Skin Cream 30g'],
    followUpDate: 'In 3 days for dressing check',
    attendingDoctor: 'Dr. Pratima Mishra, MD',
  },
  {
    id: 'vis-med-02',
    visitNumber: 'OPD-2026-4398',
    studentName: 'Aman Verma',
    studentRoll: 'REC-2023-CS089',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-102',
    visitDate: 'Today',
    visitTime: '09:30 AM',
    diagnosis: 'Acute viral pharyngitis with moderate pyrexia',
    treatment: 'Oral hydration therapy, antipyretics, antihistamines.',
    prescribedMedicines: ['Tab Dolo 650mg TDS x 3d', 'Tab Levocetirizine 5mg HS x 5d', 'Betadine Gargle 100ml'],
    followUpDate: '09 Oct 2026',
    attendingDoctor: 'Dr. Pratima Mishra, MD',
  },
  {
    id: 'vis-med-03',
    visitNumber: 'OPD-2026-4380',
    studentName: 'Mithun Sahoo',
    studentRoll: 'REC-2023-CS015',
    hostel: 'Nilgiri Residence (Block B)',
    room: 'B-205',
    visitDate: 'Yesterday',
    visitTime: '04:15 PM',
    diagnosis: 'Acute acute gastroenteritis with mild dehydration',
    treatment: 'ORS electrolyte replenishment, probiotics, antispasmodic.',
    prescribedMedicines: ['Electral ORS 4.2g x 5 sachets', 'Cap Econorm 250mg BD x 3d', 'Tab Drotikind 40mg SOS'],
    attendingDoctor: 'Dr. Pratima Mishra, MD',
  },
];

export const INITIAL_MEDICAL_LEAVES: MedicalLeaveRecord[] = [
  {
    id: 'ml-01',
    leaveNumber: 'MED-LV-2026-042',
    studentName: 'Aman Verma',
    studentRoll: 'REC-2023-CS089',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-102',
    startDate: '06 Oct 2026',
    endDate: '08 Oct 2026',
    days: 3,
    operationalReason: 'Acute viral febrile illness — 3 days hostel room recuperation advised by CMO.',
    medicalStatus: 'APPROVED_BY_WARDEN',
    recommendedBy: 'Dr. Pratima Mishra, MD',
    wardenNotified: true,
    isFitToResume: false,
  },
  {
    id: 'ml-02',
    leaveNumber: 'MED-LV-2026-039',
    studentName: 'Pritam Mohanty',
    studentRoll: 'REC-2023-CS044',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-210',
    startDate: '06 Oct 2026',
    endDate: '12 Oct 2026',
    days: 7,
    operationalReason: 'Surgical referral recuperation (Hospitalized at AIIMS). Extended hostel leave required.',
    medicalStatus: 'RECOMMENDED',
    recommendedBy: 'Dr. Pratima Mishra, MD',
    wardenNotified: true,
    isFitToResume: false,
  },
  {
    id: 'ml-03',
    leaveNumber: 'MED-LV-2026-035',
    studentName: 'Mithun Sahoo',
    studentRoll: 'REC-2023-CS015',
    hostel: 'Nilgiri Residence (Block B)',
    room: 'B-205',
    startDate: '03 Oct 2026',
    endDate: '05 Oct 2026',
    days: 2,
    operationalReason: 'Acute gastroenteritis bed rest — complete recovery verified.',
    medicalStatus: 'EXPIRED',
    recommendedBy: 'Dr. Pratima Mishra, MD',
    wardenNotified: true,
    isFitToResume: true,
  },
];

export const INITIAL_MEDICINE_INVENTORY: MedicineInventoryItem[] = [
  {
    id: 'med-inv-01',
    code: 'MED-DOLO-650',
    name: 'Paracetamol (Dolo 650mg)',
    category: 'Antipyretic',
    dosage: '650mg Tab',
    quantity: 140,
    unit: 'Strips',
    minStock: 50,
    expiryDate: '12/2027',
    isLowStock: false,
    isExpiringSoon: false,
    location: 'Pharmacy Cabinet A-1',
  },
  {
    id: 'med-inv-02',
    code: 'MED-CET-10',
    name: 'Cetirizine HCl (Alen OD 10mg)',
    category: 'Antihistamine',
    dosage: '10mg Tab',
    quantity: 85,
    unit: 'Strips',
    minStock: 30,
    expiryDate: '08/2027',
    isLowStock: false,
    isExpiringSoon: false,
    location: 'Pharmacy Cabinet A-2',
  },
  {
    id: 'med-inv-03',
    code: 'MED-ORS-ELC',
    name: 'WHO Formulation Oral Rehydration Salts (Electral)',
    category: 'Electrolyte',
    dosage: '21.8g Sachet',
    quantity: 12,
    unit: 'Sachets',
    minStock: 40,
    expiryDate: '04/2027',
    isLowStock: true,
    isExpiringSoon: false,
    location: 'Pharmacy Cabinet B-3',
  },
  {
    id: 'med-inv-04',
    code: 'MED-BET-100',
    name: 'Povidone-Iodine Antiseptic Solution 5% (Betadine)',
    category: 'First Aid',
    dosage: '100ml Bottle',
    quantity: 6,
    unit: 'Bottles',
    minStock: 15,
    expiryDate: '11/2026',
    isLowStock: true,
    isExpiringSoon: true,
    location: 'Dressing Room Bay 1',
  },
  {
    id: 'med-inv-05',
    code: 'MED-AZI-500',
    name: 'Azithromycin (Azee 500mg)',
    category: 'Antibiotic',
    dosage: '500mg Tab',
    quantity: 45,
    unit: 'Strips',
    minStock: 25,
    expiryDate: '03/2028',
    isLowStock: false,
    isExpiringSoon: false,
    location: 'Locked Schedule H Safe',
  },
  {
    id: 'med-inv-06',
    code: 'MED-VOL-50',
    name: 'Diclofenac Sodium Gel (Volini Pain Relief)',
    category: 'Ointment',
    dosage: '50g Tube',
    quantity: 22,
    unit: 'Tubes',
    minStock: 20,
    expiryDate: '06/2027',
    isLowStock: false,
    isExpiringSoon: false,
    location: 'Pharmacy Cabinet C-1',
  },
];

export const INITIAL_AMBULANCE_REFERRALS: AmbulanceReferralRecord[] = [
  {
    id: 'amb-ref-01',
    referralNumber: 'REF-2026-018',
    studentName: 'Pritam Mohanty',
    studentRoll: 'REC-2023-CS044',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-210',
    dispatchTime: 'Today, 07:40 AM',
    vehicleNumber: 'OD-02-AMB-108 (Campus 24x7 Ambulance)',
    driverName: 'Kailash Nayak',
    driverPhone: '+91 94370 00108',
    destinationHospital: 'AIIMS Bhubaneswar Emergency Surgical Wing',
    referralReason: 'Acute abdominal emergency (Suspected appendicitis / peritonitis)',
    accompanyingStaff: 'Male Nurse Ranjan Jena',
    emergencyContactCalled: true,
    status: 'ADMITTED',
  },
  {
    id: 'amb-ref-02',
    referralNumber: 'REF-2026-014',
    studentName: 'Debashis Rout',
    studentRoll: 'REC-2023-CS088',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-101',
    dispatchTime: '01 Oct 2026, 02:15 PM',
    vehicleNumber: 'OD-02-AMB-108',
    driverName: 'Kailash Nayak',
    driverPhone: '+91 94370 00108',
    destinationHospital: 'Capital Hospital (Trauma Care)',
    referralReason: 'Sports ankle ligament rupture requiring X-ray imaging and plaster cast',
    accompanyingStaff: 'Warden Representative B. Swain',
    emergencyContactCalled: true,
    status: 'COMPLETED',
  },
];

export const INITIAL_MEDICAL_REPORTS: MedicalReportItem[] = [
  {
    id: 'rep-med-01',
    name: 'Daily OPD Footfall & Clinical Consultation Summary',
    category: 'OPD_CONSULTATION',
    recordCount: 42,
    description: 'Patient registrations, vitals recorded, fever screenings, and prescriptions dispensed.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-med-02',
    name: 'Campus Emergency SOS Response & Ambulance Log',
    category: 'EMERGENCY_AMBULANCE',
    recordCount: 8,
    description: 'Distress triggers, ambulance dispatch turnaround minutes, and hospital referrals.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-med-03',
    name: 'Medical Leave Recommendations & Hostel Notifications',
    category: 'MEDICAL_LEAVE',
    recordCount: 16,
    description: 'Warden-cleared recuperation rest periods, communicable disease tracking, and resumption fitness.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-med-04',
    name: 'Pharmacy Consumption & Essential Medicine Stock Audit',
    category: 'PHARMACY',
    recordCount: 55,
    description: 'Analgesics, antibiotics, ORS sachets, expiry date watch-list, and purchase requisitions.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-med-05',
    name: 'Hostel Illness Epidemiology & Fever Cluster Surveillance',
    category: 'EPIDEMIOLOGY',
    recordCount: 24,
    description: 'Hostel block wise breakdown of viral fevers, seasonal allergies, and gastro complaints.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-med-06',
    name: 'Annual Student Health Screening & Physical Fitness Register',
    category: 'HEALTH_CHECKUP',
    recordCount: 120,
    description: 'Blood pressure baselines, BMI indices, vision tests, and chronic allergy registries.',
    generatedDate: 'Today',
    format: 'CSV',
  },
];
