import {
  ServiceStaffProfile,
  ServiceRequest,
  MaintenanceScheduleItem,
  ServiceInventoryItem,
  ServiceReportItem,
} from './types';

export const INITIAL_SERVICE_STAFF: ServiceStaffProfile = {
  name: 'Mahendra Singh',
  badgeId: 'OPS-MAINT-108',
  designation: 'Campus Operations & Maintenance Supervisor',
  department: 'Estate & Campus Facilities',
  phone: '+91 94370 77102',
  shift: 'General Operations (08:00 AM - 05:00 PM)',
  assignedZone: 'Nilgiri Hostels, Dining Mess & Academic Blocks',
  emergencyHelpline: '+91 94370 00115',
  avatarUrl: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=160',
};

export const INITIAL_SERVICE_REQUESTS: ServiceRequest[] = [
  {
    id: 'sr-101',
    ticketNumber: 'SR-2026-1042',
    studentName: 'Subham Pradhan',
    studentId: 'CS2023042',
    studentRoll: 'REC-2023-CS042',
    studentPhone: '+91 98765 43210',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-204',
    category: 'Plumbing',
    title: 'Washroom water tap continuous dripping & low pressure',
    description: 'The bathroom washbasin mixer tap in Room A-204 is continuously leaking clean water and has low pressure.',
    priority: 'HIGH',
    assignedStaffId: 'staff-plumb-01',
    assignedStaffName: 'Mahendra Singh (Lead Plumber)',
    status: 'In Progress',
    createdTime: 'Today, 09:15 AM',
    updatedTime: 'Today, 10:30 AM',
    slaDue: 'Today by 02:00 PM',
    photoUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400',
    completionNote: 'Inspected washer seal. Replacing brass tap cartridge.',
  },
  {
    id: 'sr-102',
    ticketNumber: 'SR-2026-1045',
    studentName: 'Aman Verma',
    studentId: 'CS2023089',
    studentRoll: 'REC-2023-CS089',
    studentPhone: '+91 98610 99881',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-102',
    category: 'Electrical',
    title: 'Ceiling fan regulator sparking and speed not changing',
    description: 'Ceiling fan switch box sparked while rotating speed knob. Currently stuck on speed 5 with buzzing sound.',
    priority: 'CRITICAL',
    assignedStaffId: 'staff-elec-01',
    assignedStaffName: 'Dillip Das (Electrician)',
    status: 'Assigned',
    createdTime: 'Today, 10:00 AM',
    updatedTime: 'Today, 10:15 AM',
    slaDue: 'Within 2 hours',
  },
  {
    id: 'sr-103',
    ticketNumber: 'SR-2026-1038',
    studentName: 'Mithun Sahoo',
    studentId: 'CS2023015',
    studentRoll: 'REC-2023-CS015',
    studentPhone: '+91 98765 88991',
    hostel: 'Nilgiri Residence (Block B)',
    room: 'B-205',
    category: 'Wi-Fi',
    title: 'Corridor Wi-Fi Access Point frequent disconnections',
    description: '2nd floor east wing corridor AP frequently drops packets during online lab exams and study hours.',
    priority: 'MEDIUM',
    assignedStaffId: 'staff-net-01',
    assignedStaffName: 'Suresh Kumar (Network Tech)',
    status: 'Accepted',
    createdTime: 'Today, 08:30 AM',
    updatedTime: 'Today, 09:00 AM',
    slaDue: 'Today by 04:00 PM',
  },
  {
    id: 'sr-104',
    ticketNumber: 'SR-2026-1029',
    studentName: 'Rohan Jena',
    studentId: 'EE2022031',
    studentRoll: 'REC-2022-EE031',
    studentPhone: '+91 98532 11009',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-301',
    category: 'Furniture',
    title: 'Study table hinge broken & wardrobe lock jammed',
    description: 'The right side hinge of the wooden study desk is detached, and the wardrobe key cylinder is sticking.',
    priority: 'LOW',
    assignedStaffId: 'staff-carp-01',
    assignedStaffName: 'Baidhar Rout (Carpenter)',
    status: 'New',
    createdTime: 'Today, 07:45 AM',
    updatedTime: 'Today, 07:45 AM',
    slaDue: 'Tomorrow by 12:00 PM',
  },
  {
    id: 'sr-105',
    ticketNumber: 'SR-2026-1012',
    studentName: 'Pritam Mohanty',
    studentId: 'CS2023044',
    studentRoll: 'REC-2023-CS044',
    studentPhone: '+91 98765 11223',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-210',
    category: 'Cleaning',
    title: 'Washroom deep sanitization & drain clearance',
    description: 'Floor drain pipe slow drainage and foul smell after rainfall.',
    priority: 'MEDIUM',
    assignedStaffId: 'staff-clean-01',
    assignedStaffName: 'Ramesh Behera (Housekeeping Lead)',
    status: 'Resolved',
    createdTime: 'Yesterday, 02:00 PM',
    updatedTime: 'Today, 09:30 AM',
    slaDue: 'Completed',
    completionNote: 'Drain unblocked with chemical flusher, deep disinfectant applied.',
    studentFeedback: 'Verified clean by student. Water flowing freely now.',
    rating: 5,
  },
  {
    id: 'sr-106',
    ticketNumber: 'SR-2026-0995',
    studentName: 'Debashis Rout',
    studentId: 'CS2023088',
    studentRoll: 'REC-2023-CS088',
    studentPhone: '+91 94371 99221',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-101',
    category: 'Water',
    title: 'RO Water Purifier filter indicator blinking red',
    description: 'Ground floor Nilgiri Block A water cooler display shows service needed and low flow rate.',
    priority: 'HIGH',
    assignedStaffId: 'staff-plumb-01',
    assignedStaffName: 'Mahendra Singh (Lead Plumber)',
    status: 'Student Confirmed',
    createdTime: 'Yesterday, 11:00 AM',
    updatedTime: 'Yesterday, 05:00 PM',
    slaDue: 'Closed',
    completionNote: 'Replaced sediment & carbon filters, tested TDS reading (110 ppm, safe drinking).',
    studentFeedback: 'Cold clean water restored, thank you!',
    rating: 5,
  },
];

export const INITIAL_MAINTENANCE_SCHEDULE: MaintenanceScheduleItem[] = [
  {
    id: 'maint-01',
    title: 'Hostel RO Purifier TDS & UV Chamber Inspection',
    facility: 'Nilgiri Block A & B Coolers',
    category: 'Water',
    scheduledTime: 'Daily (08:30 AM - 10:30 AM)',
    assignedTeam: 'Plumbing & Water Team',
    frequency: 'Daily',
    status: 'COMPLETED',
  },
  {
    id: 'maint-02',
    title: 'Solar Water Heater & Geyser Electrical Safety Audit',
    facility: 'Nilgiri Block A Rooftop',
    category: 'Electrical',
    scheduledTime: 'Today (11:00 AM - 01:00 PM)',
    assignedTeam: 'High Voltage Team',
    frequency: 'Weekly',
    status: 'IN_PROGRESS',
  },
  {
    id: 'maint-03',
    title: 'Mess Exhaust Duct Cleaning & Grease Trap Flusher',
    facility: 'Central Dining Mess 1 Kitchen',
    category: 'Mess',
    scheduledTime: 'Today (03:30 PM - 05:30 PM)',
    assignedTeam: 'Mess Facilities Team',
    frequency: 'Weekly',
    status: 'PENDING',
  },
  {
    id: 'maint-04',
    title: 'Overhead Water Tank Chlorination & Float Valve Check',
    facility: 'Campus Water Tower Reservoir',
    category: 'Plumbing',
    scheduledTime: 'Tomorrow (06:00 AM - 09:00 AM)',
    assignedTeam: 'Public Health Sanitation Team',
    frequency: 'Monthly',
    status: 'PENDING',
  },
];

export const INITIAL_SERVICE_INVENTORY: ServiceInventoryItem[] = [
  {
    id: 'inv-01',
    itemCode: 'ELE-LED-18W',
    name: '18W LED Batten Tube Light (Philips Cool Daylight)',
    category: 'Electrical',
    quantity: 42,
    unit: 'Pieces',
    minStock: 20,
    location: 'Electrical Store Bay A-3',
    condition: 'GOOD',
    lastRestocked: '01 Oct 2026',
    isLowStock: false,
  },
  {
    id: 'inv-02',
    itemCode: 'PLB-TAP-BRS',
    name: 'Heavy Brass Half-Turn Bib Cock Tap (Jaguar 15mm)',
    category: 'Plumbing',
    quantity: 6,
    unit: 'Pieces',
    minStock: 15,
    location: 'Plumbing Racks Bay B-1',
    condition: 'GOOD',
    lastRestocked: '25 Sep 2026',
    isLowStock: true,
  },
  {
    id: 'inv-03',
    itemCode: 'NET-CAT6-305',
    name: 'D-Link Cat6 UTP Solid LAN Cable Reel (305m)',
    category: 'Wi-Fi',
    quantity: 3,
    unit: 'Rolls',
    minStock: 2,
    location: 'IT Storage Rack C-2',
    condition: 'GOOD',
    lastRestocked: '28 Sep 2026',
    isLowStock: false,
  },
  {
    id: 'inv-04',
    itemCode: 'CLN-DIS-5L',
    name: 'Hospital-Grade Phenyle Disinfectant Concentrate (5L)',
    category: 'Cleaning',
    quantity: 4,
    unit: 'Cans',
    minStock: 10,
    location: 'Housekeeping Shed H-1',
    condition: 'GOOD',
    lastRestocked: '18 Sep 2026',
    isLowStock: true,
  },
  {
    id: 'inv-05',
    itemCode: 'ELE-MCB-16A',
    name: 'Schneider C-Curve Single Pole 16A MCB Breaker',
    category: 'Electrical',
    quantity: 28,
    unit: 'Units',
    minStock: 12,
    location: 'Electrical Store Bay A-1',
    condition: 'GOOD',
    lastRestocked: '02 Oct 2026',
    isLowStock: false,
  },
  {
    id: 'inv-06',
    itemCode: 'WTR-RO-MEM',
    name: 'Commercial Dow Filmtec 100 GPD RO Membrane Filter',
    category: 'Water',
    quantity: 5,
    unit: 'Pieces',
    minStock: 8,
    location: 'Water Treatment Store Bay W-2',
    condition: 'GOOD',
    lastRestocked: '20 Sep 2026',
    isLowStock: true,
  },
];

export const INITIAL_SERVICE_REPORTS: ServiceReportItem[] = [
  {
    id: 'rep-srv-01',
    name: 'Daily Service & Maintenance Clearance Report',
    category: 'OPERATIONS',
    recordCount: 38,
    description: 'Summary of all tickets resolved, pending, and escalated across electrical, plumbing, and Wi-Fi.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-srv-02',
    name: 'Hostel Maintenance & Repair SLA Audit',
    category: 'SLA_COMPLIANCE',
    recordCount: 52,
    description: 'Turnaround duration analysis with percentage of tickets resolved within 4-hour SLA.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-srv-03',
    name: 'Inventory Consumption & Low Stock Reorder Register',
    category: 'INVENTORY',
    recordCount: 26,
    description: 'Spare parts depleted, critical items below minimum threshold, and purchase requisitions.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-srv-04',
    name: 'Mess Facilities & Kitchen Equipment Hygiene Audit',
    category: 'MESS',
    recordCount: 14,
    description: 'Deep cleaning schedule, commercial burners, cold storage refrigeration, and dishwasher logs.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-srv-05',
    name: 'Resident Feedback & Satisfaction Scorecard',
    category: 'QUALITY',
    recordCount: 45,
    description: 'Student star ratings and comments following completion of hostel room repairs.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-srv-06',
    name: 'Quarterly Asset & Preventive Maintenance Ledger',
    category: 'PREVENTIVE',
    recordCount: 80,
    description: 'Overhead tanks, transformer substations, diesel generator sets, and fire hydrants.',
    generatedDate: 'Today',
    format: 'CSV',
  },
];
