import {
  WardenProfile,
  GatePass,
  Resident,
  Room,
  RoomChangeRequest,
  RollCallRecord,
  CurfewViolation,
  HostelComplaint,
  MessMenuDay,
  MessFeedback,
  MealChangeRequest,
  VisitorRequest,
  DisciplinaryRecord,
  HostelEmergency,
  HostelNotice,
  FacilityTiming,
  WardenLeave,
  HostelStaff,
  LeaveRequestItem,
  StudentMovementRecord,
  MaintenanceTicketItem,
  HostelReportItem,
} from './types';

export const INITIAL_WARDEN_PROFILE: WardenProfile = {
  id: 'warden-sahoo',
  name: 'Bhrambar Sahoo',
  empId: 'REC-WRD-042',
  email: 'sahoobhrambar700866@gmail.com',
  phone: '+91 94370 88219',
  designation: 'Chief Hostel Warden',
  assignedHostel: 'Nilgiri Boys Residence Complex',
  assignedBlocks: ['Nilgiri Block A', 'Nilgiri Block B'],
  officeRoom: 'Block A, Ground Floor, Room A-001',
  avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
  qualification: 'M.Tech in Structural Engineering, B.Tech Civil (REC Alumnus)',
  experienceYears: 12,
  emergencyContact: '+91 98610 99881 (Campus Security Desk)',
  dutyShift: 'Full-time Resident Warden (Evening & Night Roll-call On-Duty)',
  bio: 'Overseeing Nilgiri Residence Complex (Blocks A & B) housing 450+ undergraduate and postgraduate engineering residents. Committed to strict campus discipline, student safety, prompt grievance turnaround, and healthy hostel living.',
};

export const INITIAL_GATE_PASSES: GatePass[] = [
  {
    id: 'gp-101',
    passNumber: 'GP-2026-0891',
    studentId: 'REC-2023-CS042',
    studentName: 'Subham Pradhan',
    roomNumber: 'A-204',
    blockName: 'Nilgiri Block A',
    course: 'B.Tech Computer Science',
    year: '3rd Year (Sem 5)',
    type: 'DAY_PASS',
    destination: 'Bhubaneswar Central Library & Station Road',
    reason: 'GATE 2026 Exam Study Material Collection & Reference Books',
    departureDate: '2026-10-05',
    departureTime: '10:00 AM',
    expectedReturnDate: '2026-10-05',
    expectedReturnTime: '06:30 PM',
    status: 'PENDING',
    parentConsent: 'CONFIRMED',
    parentName: 'Balakrushna Pradhan',
    parentPhone: '+91 94370 88990',
    studentPhone: '+91 94380 99881',
    pastPassesCount: 6,
    qrToken: 'REC-PASS-SUBHAM-0891',
    isLateNight: false,
    appliedAt: 'Today, 08:15 AM',
  },
  {
    id: 'gp-102',
    passNumber: 'GP-2026-0892',
    studentId: 'REC-2023-CS089',
    studentName: 'Aman Verma',
    roomNumber: 'A-102',
    blockName: 'Nilgiri Block A',
    course: 'B.Tech CSE',
    year: '2nd Year (Sem 3)',
    type: 'NIGHT_LEAVE',
    destination: 'Home Town (Cuttack, CDA Sector 9)',
    reason: 'Family Puja and Medical Checkup with Parents',
    departureDate: '2026-10-05',
    departureTime: '04:00 PM',
    expectedReturnDate: '2026-10-07',
    expectedReturnTime: '08:00 AM',
    status: 'PENDING',
    parentConsent: 'OTP_VERIFIED',
    parentName: 'Sunil Verma',
    parentPhone: '+91 98123 45678',
    studentPhone: '+91 91234 56780',
    pastPassesCount: 3,
    qrToken: 'REC-PASS-AMAN-0892',
    isLateNight: false,
    appliedAt: 'Today, 07:45 AM',
  },
  {
    id: 'gp-103',
    passNumber: 'GP-2026-0888',
    studentId: 'REC-2024-ME014',
    studentName: 'Mithun Sahoo',
    roomNumber: 'B-205',
    blockName: 'Nilgiri Block B',
    course: 'B.Tech Mechanical',
    year: '2nd Year (Sem 3)',
    type: 'DAY_PASS',
    destination: 'Infocity IT Park & Hackathon Hub',
    reason: 'Inter-College Autonomous Robotics Workshop and Hackathon meet',
    departureDate: '2026-10-05',
    departureTime: '09:00 AM',
    expectedReturnDate: '2026-10-05',
    expectedReturnTime: '07:00 PM',
    actualDepartureTime: '09:05 AM',
    status: 'OUT',
    parentConsent: 'CONFIRMED',
    parentName: 'Baidhar Sahoo',
    parentPhone: '+91 70086 61234',
    studentPhone: '+91 70086 69999',
    pastPassesCount: 11,
    qrToken: 'REC-PASS-MITHUN-0888',
    isLateNight: false,
    appliedAt: 'Yesterday, 06:30 PM',
  },
  {
    id: 'gp-104',
    passNumber: 'GP-2026-0885',
    studentId: 'REC-2022-EE031',
    studentName: 'Rohan Jena',
    roomNumber: 'A-301',
    blockName: 'Nilgiri Block A',
    course: 'B.Tech Electrical',
    year: '4th Year (Sem 7)',
    type: 'DAY_PASS',
    destination: 'Patia Market Complex',
    reason: 'Hardware components purchase for Final Year Capstone Project',
    departureDate: '2026-10-04',
    departureTime: '04:00 PM',
    expectedReturnDate: '2026-10-04',
    expectedReturnTime: '08:30 PM',
    actualDepartureTime: '04:12 PM',
    status: 'OVERDUE',
    overdueMinutes: 195,
    parentConsent: 'CONFIRMED',
    parentName: 'Kabindra Jena',
    parentPhone: '+91 94371 55667',
    studentPhone: '+91 98532 11009',
    pastPassesCount: 14,
    qrToken: 'REC-PASS-ROHAN-0885',
    isLateNight: true,
    appliedAt: '2026-10-04, 02:00 PM',
  },
  {
    id: 'gp-105',
    passNumber: 'GP-2026-0870',
    studentId: 'REC-2023-EC019',
    studentName: 'Pritam Mohanty',
    roomNumber: 'B-108',
    blockName: 'Nilgiri Block B',
    course: 'B.Tech ECE',
    year: '3rd Year (Sem 5)',
    type: 'WEEKEND_PASS',
    destination: 'Rourkela (Home)',
    reason: 'Sister marriage ceremony and leave',
    departureDate: '2026-10-02',
    departureTime: '02:00 PM',
    expectedReturnDate: '2026-10-04',
    expectedReturnTime: '09:00 PM',
    actualDepartureTime: '02:15 PM',
    actualReturnTime: '08:45 PM',
    status: 'RETURNED',
    parentConsent: 'CONFIRMED',
    parentName: 'Dillip Mohanty',
    parentPhone: '+91 94370 77123',
    studentPhone: '+91 99370 44556',
    pastPassesCount: 5,
    qrToken: 'REC-PASS-PRITAM-0870',
    isLateNight: false,
    appliedAt: '2026-10-01, 11:30 AM',
  },
];

export const INITIAL_RESIDENTS: Resident[] = [
  {
    id: 'res-1',
    studentId: 'REC-2023-CS042',
    name: 'Subham Pradhan',
    roomNumber: 'A-204',
    bedNumber: 'Bed A',
    blockName: 'Nilgiri Block A',
    hostelName: 'Nilgiri Boys Hostel',
    branch: 'Computer Science & Engineering',
    year: '3rd Year (Sem 5)',
    phone: '+91 94380 99881',
    email: 'subhampradhan34864@gmail.com',
    guardianName: 'Balakrushna Pradhan (Father) & Nirupama Pradhan (Mother)',
    guardianPhone: '+91 94370 88990',
    guardianRelation: 'Father / Mother',
    presenceStatus: 'IN_HOSTEL',
    bloodGroup: 'B+',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    duesPending: 0,
    kycStatus: 'VERIFIED',
    emergencyContact: '+91 98610 12345',
  },
  {
    id: 'res-2',
    studentId: 'REC-2023-CS089',
    name: 'Aman Verma',
    roomNumber: 'A-102',
    bedNumber: 'Bed B',
    blockName: 'Nilgiri Block A',
    hostelName: 'Nilgiri Boys Hostel',
    branch: 'Computer Science & Engineering',
    year: '2nd Year (Sem 3)',
    phone: '+91 91234 56780',
    email: 'aman.4211@rec.ac.in',
    guardianName: 'Sunil Verma (Father)',
    guardianPhone: '+91 98123 45678',
    guardianRelation: 'Father',
    presenceStatus: 'IN_HOSTEL',
    bloodGroup: 'O+',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    duesPending: 1200,
    kycStatus: 'VERIFIED',
    emergencyContact: '+91 98123 45678',
  },
  {
    id: 'res-3',
    studentId: 'REC-2024-ME014',
    name: 'Mithun Sahoo',
    roomNumber: 'B-205',
    bedNumber: 'Bed A',
    blockName: 'Nilgiri Block B',
    hostelName: 'Nilgiri Boys Hostel',
    branch: 'Mechanical Engineering',
    year: '2nd Year (Sem 3)',
    phone: '+91 70086 69999',
    email: 'sahoomithun700866@gmail.com',
    guardianName: 'Baidhar Sahoo (Father)',
    guardianPhone: '+91 70086 61234',
    guardianRelation: 'Father',
    presenceStatus: 'OUT_ON_PASS',
    bloodGroup: 'A+',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    duesPending: 0,
    kycStatus: 'VERIFIED',
    emergencyContact: '+91 70086 61234',
  },
  {
    id: 'res-4',
    studentId: 'REC-2022-EE031',
    name: 'Rohan Jena',
    roomNumber: 'A-301',
    bedNumber: 'Bed A',
    blockName: 'Nilgiri Block A',
    hostelName: 'Nilgiri Boys Hostel',
    branch: 'Electrical Engineering',
    year: '4th Year (Sem 7)',
    phone: '+91 98532 11009',
    email: 'rohan.jena@rec.ac.in',
    guardianName: 'Kabindra Jena (Father)',
    guardianPhone: '+91 94371 55667',
    guardianRelation: 'Father',
    presenceStatus: 'OVERDUE',
    bloodGroup: 'AB+',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    duesPending: 3500,
    kycStatus: 'VERIFIED',
    emergencyContact: '+91 94371 55667',
  },
  {
    id: 'res-5',
    studentId: 'REC-2023-EC019',
    name: 'Pritam Mohanty',
    roomNumber: 'B-108',
    bedNumber: 'Bed B',
    blockName: 'Nilgiri Block B',
    hostelName: 'Nilgiri Boys Hostel',
    branch: 'Electronics & Communication',
    year: '3rd Year (Sem 5)',
    phone: '+91 99370 44556',
    email: 'pritam.ec@rec.ac.in',
    guardianName: 'Dillip Mohanty (Father)',
    guardianPhone: '+91 94370 77123',
    guardianRelation: 'Father',
    presenceStatus: 'IN_HOSTEL',
    bloodGroup: 'O-',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150',
    duesPending: 0,
    kycStatus: 'VERIFIED',
    emergencyContact: '+91 94370 77123',
  },
  {
    id: 'res-6',
    studentId: 'REC-2024-CS110',
    name: 'Ananya Tripathy',
    roomNumber: 'B-302',
    bedNumber: 'Bed A',
    blockName: 'Nilgiri Block B',
    hostelName: 'Nilgiri Boys Hostel',
    branch: 'Computer Science & Engineering',
    year: '1st Year (Sem 1)',
    phone: '+91 94391 22334',
    email: 'ananya.t@rec.ac.in',
    guardianName: 'Bikram Tripathy (Father)',
    guardianPhone: '+91 94380 88771',
    guardianRelation: 'Father',
    presenceStatus: 'IN_HOSTEL',
    bloodGroup: 'B-',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    duesPending: 0,
    kycStatus: 'VERIFIED',
    emergencyContact: '+91 94380 88771',
  },
];

export const INITIAL_ROOMS: Room[] = [
  {
    roomNumber: 'A-101',
    blockName: 'Nilgiri Block A',
    floor: 1,
    capacity: 2,
    occupiedCount: 2,
    type: 'DOUBLE',
    status: 'FULL',
    beds: [
      { bedNumber: 'Bed A', isOccupied: true, residentName: 'Debashis Rout', studentId: 'REC-2023-CS011' },
      { bedNumber: 'Bed B', isOccupied: true, residentName: 'Sourav Nayak', studentId: 'REC-2023-CS018' },
    ],
    inventory: { fans: 2, lights: 3, tables: 2, chairs: 2, cupboards: 2, condition: 'EXCELLENT' },
  },
  {
    roomNumber: 'A-102',
    blockName: 'Nilgiri Block A',
    floor: 1,
    capacity: 2,
    occupiedCount: 1,
    type: 'DOUBLE',
    status: 'AVAILABLE',
    beds: [
      { bedNumber: 'Bed A', isOccupied: false },
      { bedNumber: 'Bed B', isOccupied: true, residentName: 'Aman Verma', studentId: 'REC-2023-CS089' },
    ],
    inventory: { fans: 2, lights: 3, tables: 2, chairs: 2, cupboards: 2, condition: 'GOOD' },
  },
  {
    roomNumber: 'A-204',
    blockName: 'Nilgiri Block A',
    floor: 2,
    capacity: 2,
    occupiedCount: 2,
    type: 'DOUBLE',
    status: 'FULL',
    beds: [
      { bedNumber: 'Bed A', isOccupied: true, residentName: 'Subham Pradhan', studentId: 'REC-2023-CS042' },
      { bedNumber: 'Bed B', isOccupied: true, residentName: 'Sanjay Mishra', studentId: 'REC-2023-CS045' },
    ],
    inventory: { fans: 2, lights: 3, tables: 2, chairs: 2, cupboards: 2, condition: 'GOOD' },
  },
  {
    roomNumber: 'A-301',
    blockName: 'Nilgiri Block A',
    floor: 3,
    capacity: 2,
    occupiedCount: 1,
    type: 'DOUBLE',
    status: 'AVAILABLE',
    beds: [
      { bedNumber: 'Bed A', isOccupied: true, residentName: 'Rohan Jena', studentId: 'REC-2022-EE031' },
      { bedNumber: 'Bed B', isOccupied: false },
    ],
    inventory: { fans: 2, lights: 2, tables: 2, chairs: 1, cupboards: 2, condition: 'NEEDS_REPAIR' },
  },
  {
    roomNumber: 'B-108',
    blockName: 'Nilgiri Block B',
    floor: 1,
    capacity: 2,
    occupiedCount: 2,
    type: 'DOUBLE',
    status: 'FULL',
    beds: [
      { bedNumber: 'Bed A', isOccupied: true, residentName: 'Abhilash Biswal', studentId: 'REC-2023-EC008' },
      { bedNumber: 'Bed B', isOccupied: true, residentName: 'Pritam Mohanty', studentId: 'REC-2023-EC019' },
    ],
    inventory: { fans: 2, lights: 3, tables: 2, chairs: 2, cupboards: 2, condition: 'EXCELLENT' },
  },
  {
    roomNumber: 'B-205',
    blockName: 'Nilgiri Block B',
    floor: 2,
    capacity: 2,
    occupiedCount: 2,
    type: 'DOUBLE',
    status: 'FULL',
    beds: [
      { bedNumber: 'Bed A', isOccupied: true, residentName: 'Mithun Sahoo', studentId: 'REC-2024-ME014' },
      { bedNumber: 'Bed B', isOccupied: true, residentName: 'Alok Panda', studentId: 'REC-2024-ME022' },
    ],
    inventory: { fans: 2, lights: 3, tables: 2, chairs: 2, cupboards: 2, condition: 'GOOD' },
  },
];

export const INITIAL_ROOM_REQUESTS: RoomChangeRequest[] = [
  {
    id: 'rc-1',
    studentId: 'REC-2023-CS089',
    studentName: 'Aman Verma',
    currentRoom: 'A-102 (Bed B)',
    requestedRoom: 'A-204 (Bed B)',
    reason: 'Requesting room shift to stay closer to department project teammates in 2nd floor.',
    date: '2026-10-04',
    status: 'PENDING',
    conflictNote: 'No disciplinary complaints; both roommates gave written consent.',
  },
  {
    id: 'rc-2',
    studentId: 'REC-2024-ME014',
    studentName: 'Mithun Sahoo',
    currentRoom: 'B-205',
    requestedRoom: 'A-202 (Silent Study Wing)',
    reason: 'Medical allergy to damp wall near window in current room; doctor recommended dry room.',
    date: '2026-10-03',
    status: 'APPROVED',
  },
];

export const INITIAL_ROLL_CALLS: RollCallRecord[] = [
  {
    id: 'rc-rec-01',
    date: '2026-10-04',
    blockName: 'Nilgiri Block A',
    floor: 'Floor 2 (Rooms 201-220)',
    conductedBy: 'Bhrambar Sahoo (Chief Warden)',
    timeTaken: '09:45 PM',
    totalResidents: 40,
    presentCount: 37,
    absentCount: 1,
    onPassCount: 2,
    entries: [
      { studentId: 'REC-2023-CS042', name: 'Subham Pradhan', roomNumber: 'A-204', status: 'PRESENT' },
      { studentId: 'REC-2022-EE031', name: 'Rohan Jena', roomNumber: 'A-301', status: 'ABSENT', remark: 'Not in room at 9:45 PM. Door locked.', guardianAlertSent: true },
      { studentId: 'REC-2024-ME014', name: 'Mithun Sahoo', roomNumber: 'B-205', status: 'ON_PASS', remark: 'On official Robotics pass GP-0888' },
    ],
  },
];

export const INITIAL_CURFEW_VIOLATIONS: CurfewViolation[] = [
  {
    id: 'cv-1',
    studentId: 'REC-2022-EE031',
    studentName: 'Rohan Jena',
    roomNumber: 'A-301',
    blockName: 'Nilgiri Block A',
    date: '2026-10-04',
    expectedTime: '08:30 PM',
    actualEntryTime: 'Still Not Returned (Overdue)',
    lateMinutes: 195,
    reason: 'Delayed at Patia marketplace without gate intimation',
    violationCount: 3,
    isRepeatViolator: true,
    penaltyStatus: 'PARENT_CALLED',
  },
  {
    id: 'cv-2',
    studentId: 'REC-2023-CS011',
    studentName: 'Debashis Rout',
    roomNumber: 'A-101',
    blockName: 'Nilgiri Block A',
    date: '2026-10-02',
    expectedTime: '09:30 PM',
    actualEntryTime: '10:15 PM',
    lateMinutes: 45,
    reason: 'City bus breakdown near Khandagiri square',
    violationCount: 1,
    isRepeatViolator: false,
    penaltyStatus: 'WARNING_ISSUED',
  },
];

export const INITIAL_COMPLAINTS: HostelComplaint[] = [
  {
    id: 'cmp-101',
    ticketNumber: 'CMP-WRD-0921',
    studentName: 'Subham Pradhan',
    roomNumber: 'A-204',
    blockName: 'Nilgiri Block A',
    category: 'WIFI_INTERNET',
    title: 'Wi-Fi Access Point 2nd Floor Corrupted / Zero Signal',
    description: 'The Cisco AP outside room A-204 is blinking orange. Speeds dropping to 0 Mbps during evening study hours.',
    photoUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=300',
    status: 'ASSIGNED',
    priority: 'HIGH',
    assignedTo: 'Suresh Kumar (Network Engg)',
    technicianPhone: '+91 94370 12044',
    createdAt: '2026-10-03',
    ageDays: 2,
    isOverdue: false,
    isReopened: false,
    isRepeat: true,
    isAnonymous: false,
  },
  {
    id: 'cmp-102',
    ticketNumber: 'CMP-WRD-0899',
    studentName: 'Rohan Jena',
    roomNumber: 'A-301',
    blockName: 'Nilgiri Block A',
    category: 'PLUMBING',
    title: 'Continuous Water Tank Overflow & Bathroom Tap Leak',
    description: 'Tap in 3rd floor washroom valve 3 is stuck open causing water leakage on the corridor floor.',
    photoUrl: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=300',
    status: 'IN_PROGRESS',
    priority: 'EMERGENCY',
    assignedTo: 'Mahendra Singh (Lead Plumber)',
    technicianPhone: '+91 94370 12045',
    createdAt: '2026-09-27',
    ageDays: 8,
    isOverdue: true,
    isReopened: true,
    isRepeat: false,
    isAnonymous: false,
  },
  {
    id: 'cmp-103',
    ticketNumber: 'CMP-WRD-0934',
    studentName: 'Anonymous Resident',
    roomNumber: 'B-Block 1st Floor',
    blockName: 'Nilgiri Block B',
    category: 'CLEANING',
    title: 'Corridor Waste Bin Not Cleared by Morning Housekeeping',
    description: 'Dry and wet garbage spilling near water cooler station B-108. Bad odor affecting nearby rooms.',
    status: 'SUBMITTED',
    priority: 'MEDIUM',
    createdAt: '2026-10-05',
    ageDays: 0,
    isOverdue: false,
    isReopened: false,
    isRepeat: false,
    isAnonymous: true,
  },
  {
    id: 'cmp-104',
    ticketNumber: 'CMP-WRD-0910',
    studentName: 'Aman Verma',
    roomNumber: 'A-102',
    blockName: 'Nilgiri Block A',
    category: 'ELECTRICAL',
    title: 'Ceiling Fan Regulator Sparking and Tube Light Flickering',
    description: 'Switchboard sparking when rotating speed knob. Potential short circuit hazard.',
    photoUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=300',
    status: 'RESOLVED',
    priority: 'HIGH',
    assignedTo: 'Suresh Kumar (Electrician)',
    technicianPhone: '+91 94370 12044',
    createdAt: '2026-10-01',
    ageDays: 4,
    isOverdue: false,
    isReopened: false,
    isRepeat: false,
    isAnonymous: false,
    resolutionNotes: 'Replaced anchor regulator capacitor and tested ground wiring. Safe now.',
  },
];

export const INITIAL_MESS_MENU: MessMenuDay[] = [
  {
    day: 'Monday',
    breakfast: 'Idli & Vada with Sambar & Coconut Chutney, Boiled Egg / Banana, Tea / Coffee',
    lunch: 'Steamed Rice, Dal Makhani, Paneer Butter Masala, Mixed Veg Fry, Curd, Salad',
    snacks: 'Veg Samosa (2 pcs) with Mint Chutney, Hot Masala Tea',
    dinner: 'Tandoori Roti, Jeera Rice, Chicken Curry (Special) / Matar Paneer, Dal Fry, Gulab Jamun',
  },
  {
    day: 'Tuesday',
    breakfast: 'Aloo Paratha with Curd & Pickle, Fresh Seasonal Fruit, Tea / Coffee',
    lunch: 'Odisha Style Dalma, Ghee Rice, Tomato Khatta, Baigan Bhaja, Papad',
    snacks: 'Poha with Sev & Roasted Peanuts, Lemon Tea',
    dinner: 'Phulka Roti, Yellow Dal Tadka, Kadai Mushroom / Egg Bhurji, Sevai Kheer',
  },
  {
    day: 'Wednesday',
    breakfast: 'Puri & Aloo Dum (Cuttack Style), Halwa, Tea / Coffee',
    lunch: 'Basmati Rice, Chana Masala, Fish Curry (Rohu) / Shahi Paneer, Cucumber Raita',
    snacks: 'Bread Pakoda with Sweet & Sour Chutney, Coffee',
    dinner: 'Veg Pulao, Chapati, Dal Fry, Chilli Chicken / Chilli Mushroom, Ice Cream',
  },
  {
    day: 'Thursday',
    breakfast: 'Uttapam with Onion & Tomato, Sambar, Fresh Juice / Milk, Tea',
    lunch: 'Lemon Rice, Sambar, Cabbage Poriyal, Dal Tadka, Appalam, Curd',
    snacks: 'Chivda Mixture, Biscuits, Hot Tea',
    dinner: 'Roti, Mixed Veg Kurma, Dal Palak, Paneer Tikka Masala, Fruit Custard',
  },
  {
    day: 'Friday',
    breakfast: 'Masala Dosa with Chutney & Sambar, Boiled Egg / Sprouts, Tea / Coffee',
    lunch: 'Steamed Rice, Rajma Masala, Aloo Gobi Fry, Boondi Raita, Roasted Papad',
    snacks: 'Aloo Chop (2 pcs) with Mustard Sauce, Tea',
    dinner: 'Biryani Special (Hyderabadi Dum Chicken Biryani / Hyderabadi Veg Dum Biryani), Mirchi Ka Salan, Raita',
    specialItem: '⭐ Friday Special Dum Biryani & Rasgulla',
  },
  {
    day: 'Saturday',
    breakfast: 'Pav Bhaji with Butter Pav, Banana, Milk, Tea / Coffee',
    lunch: 'Rice, Moong Dal Tadka, Kadhi Pakoda, Bhindi Masala, Salad',
    snacks: 'Maggi Noodles / Veg Sandwich, Tea',
    dinner: 'Tawa Roti, Dal Fry, Egg Curry / Kaju Curry, Sweet Semiya',
  },
  {
    day: 'Sunday',
    breakfast: 'Chole Bhature with Pickled Onion, Sweet Lassi / Butter Milk, Tea',
    lunch: 'Special Sunday Feast: Mutton Curry / Malai Kofta, Pulao, Dal Maharani, Rasmalai',
    snacks: 'Corn Chaat / Biscuits, Masala Tea',
    dinner: 'Light Khichdi with Ghee, Aloo Chokha, Roasted Papad, Tomato Chutney',
    isHoliday: false,
  },
];

export const INITIAL_MESS_FEEDBACK: MessFeedback = {
  rating: 4.2,
  totalReviews: 382,
  cleanlinessScore: 4.6,
  tasteScore: 4.1,
  portionScore: 4.4,
  openQualityComplaints: 2,
};

export const INITIAL_MEAL_REQUESTS: MealChangeRequest[] = [
  {
    id: 'mr-1',
    studentName: 'Subham Pradhan',
    studentId: 'REC-2023-CS042',
    roomNumber: 'A-204',
    type: 'SKIP_MEAL',
    mealDate: '2026-10-05',
    mealType: 'LUNCH',
    status: 'APPROVED',
  },
  {
    id: 'mr-2',
    studentName: 'Mithun Sahoo',
    studentId: 'REC-2024-ME014',
    roomNumber: 'B-205',
    type: 'EXTRA_GUEST_MEAL',
    mealDate: '2026-10-05',
    mealType: 'DINNER',
    guestCount: 1,
    status: 'PENDING',
  },
];

export const INITIAL_VISITORS: VisitorRequest[] = [
  {
    id: 'vis-1',
    visitorName: 'Balakrushna Pradhan',
    relation: 'Father',
    studentName: 'Subham Pradhan',
    studentRoll: 'REC-2023-CS042',
    roomNumber: 'A-204',
    phone: '+91 94370 88990',
    idProof: 'Aadhaar Card ****7819',
    entryTime: '11:00 AM',
    exitTime: '01:30 PM',
    purpose: 'Fee payment receipt submission & delivering home food',
    status: 'APPROVED',
    date: '2026-10-05',
  },
  {
    id: 'vis-2',
    visitorName: 'Sunil Verma',
    relation: 'Father',
    studentName: 'Aman Verma',
    studentRoll: 'REC-2023-CS089',
    roomNumber: 'A-102',
    phone: '+91 98123 45678',
    idProof: 'Driving License DL-OD-0291',
    entryTime: '03:30 PM',
    purpose: 'Picking up student for medical checkup at Apollo Hospital',
    status: 'PENDING',
    date: '2026-10-05',
  },
  {
    id: 'vis-3',
    visitorName: 'Unknown Outside Delivery Agent',
    relation: 'Commercial Delivery',
    studentName: 'Debashis Rout',
    studentRoll: 'REC-2023-CS011',
    roomNumber: 'A-101',
    phone: '+91 90000 11223',
    idProof: 'Company ID',
    entryTime: '08:45 PM',
    purpose: 'Unauthorized access to hostel corridor past visitor hours',
    status: 'REJECTED',
    date: '2026-10-03',
    isBlacklisted: true,
  },
];

export const INITIAL_DISCIPLINARY_RECORDS: DisciplinaryRecord[] = [
  {
    id: 'disc-1',
    studentId: 'REC-2022-EE031',
    studentName: 'Rohan Jena',
    roomNumber: 'A-301',
    incidentDate: '2026-10-04',
    category: 'CURFEW',
    severity: 'HIGH',
    description: 'Third consecutive unapproved late return past 9:30 PM gate lock without prior leave request.',
    actionTaken: 'Parent notified via phone call. Written warning letter issued. Weekend outing suspended for 2 weeks.',
    counsellingNotes: 'Student cited project stress and lack of local transport; advised to coordinate project work within campus innovation lab.',
    guardianInformed: true,
    guardianContactedOn: '2026-10-04, 10:15 PM',
  },
  {
    id: 'disc-2',
    studentId: 'REC-2024-ME022',
    studentName: 'Alok Panda',
    roomNumber: 'B-205',
    incidentDate: '2026-09-29',
    category: 'NOISE',
    severity: 'LOW',
    description: 'Playing loud music with external speaker during silent study hours (11:00 PM).',
    actionTaken: 'First verbal warning recorded. Speaker confiscated for 3 days and returned with undertaking.',
    guardianInformed: false,
  },
  {
    id: 'disc-3',
    studentId: 'ALL_RESIDENTS',
    studentName: 'General Vigilance Check',
    roomNumber: 'Nilgiri Block A & B',
    incidentDate: '2026-10-01',
    category: 'RAGGING_CHECK',
    severity: 'LOW',
    description: 'Autonomous Anti-Ragging Flying Squad surprise inspection between 11:30 PM and 01:00 AM.',
    actionTaken: 'Zero ragging or intimidation incidents detected. First-year residents reported peaceful atmosphere.',
    guardianInformed: false,
  },
];

export const INITIAL_EMERGENCIES: HostelEmergency[] = [
  {
    id: 'sos-901',
    type: 'MEDICAL_SOS',
    studentName: 'Sanjay Mishra',
    roomNumber: 'A-204',
    blockName: 'Nilgiri Block A',
    timestamp: 'Today, 03:15 AM',
    status: 'RESOLVED',
    assignedResponder: 'MEDICAL_DISPATCH',
    notes: 'Severe abdominal pain and fever. Campus medical nurse Dr. Pratima attended at 03:22 AM. Administered antispasmodic injection. Student stable and resting in room.',
    responseTimeSeconds: 420,
  },
  {
    id: 'sos-902',
    type: 'FIRE_ALARM',
    blockName: 'Nilgiri Block B',
    timestamp: '2026-09-28, 07:10 PM',
    status: 'RESOLVED',
    assignedResponder: 'FIRE_SAFETY',
    notes: 'Smoke detector triggered on 2nd floor pantry due to burnt toast. False alarm reset after inspection by Security Head Rajesh Kumar.',
    responseTimeSeconds: 180,
  },
];

export const INITIAL_NOTICES: HostelNotice[] = [
  {
    id: 'not-1',
    title: 'Strict Adherence to Hostel Curfew Timings (09:30 PM Sharp)',
    content: 'All resident students of Nilgiri Block A & B are hereby notified that the main entrance gates will strictly lock at 09:30 PM. Late entry without approved digital gate pass will result in automatic parent notification and biometric gate audit flag.',
    category: 'RULES_CURFEW',
    targetAudience: 'ALL_HOSTEL',
    date: '2026-10-03',
    deadline: 'Effective Immediately',
    isActionRequired: true,
    deliveredCount: 450,
    readCount: 428,
    actionDoneCount: 412,
    isPinned: true,
    smsFallbackSent: true,
  },
  {
    id: 'not-2',
    title: 'Routine Water Tank Cleaning & Pressure Testing Schedule',
    content: 'Overhead solar and water storage tanks in Nilgiri Block A will be chemically treated and sanitized on Wednesday, 08 Oct 2026 between 10:00 AM and 01:00 PM. Please store sufficient drinking water beforehand.',
    category: 'MAINTENANCE',
    targetAudience: 'BLOCK_A',
    date: '2026-10-04',
    deadline: '2026-10-08, 10:00 AM',
    isActionRequired: false,
    deliveredCount: 220,
    readCount: 195,
    actionDoneCount: 180,
    isPinned: false,
    smsFallbackSent: false,
  },
  {
    id: 'not-3',
    title: 'Diwali Vacation Gate Pass Pre-Registration Window Open',
    content: 'Residents intending to travel home for the upcoming autonomous festival recess must submit night leave pass requests via Campus Helper portal by 15 Oct 2026 to ensure timely parent OTP verification and room security sealing.',
    category: 'GENERAL',
    targetAudience: 'ALL_HOSTEL',
    date: '2026-10-05',
    deadline: '2026-10-15, 05:00 PM',
    isActionRequired: true,
    deliveredCount: 450,
    readCount: 310,
    actionDoneCount: 145,
    isPinned: true,
    smsFallbackSent: true,
  },
];

export const INITIAL_FACILITY_TIMINGS: FacilityTiming[] = [
  {
    id: 'fac-1',
    facilityName: 'Warden Office & Student Helpdesk',
    standardTimings: '08:00 AM - 12:00 PM & 05:00 PM - 09:00 PM',
    isOpen: true,
    openedAt: '08:00 AM',
    isTemporaryClosed: false,
  },
  {
    id: 'fac-2',
    facilityName: 'Hostel Dining Hall & Mess',
    standardTimings: 'Breakfast: 7:30-9:30 AM | Lunch: 12:30-2:30 PM | Dinner: 7:30-9:30 PM',
    isOpen: true,
    openedAt: '07:30 AM',
    isTemporaryClosed: false,
  },
  {
    id: 'fac-3',
    facilityName: 'Gymnasium & Fitness Center',
    standardTimings: 'Morning: 06:00 AM - 08:30 AM | Evening: 05:00 PM - 08:30 PM',
    isOpen: false,
    closedAt: '08:30 AM (Opens at 05:00 PM)',
    isTemporaryClosed: false,
  },
  {
    id: 'fac-4',
    facilityName: 'Hostel Night Study Room & Digital Hub',
    standardTimings: '24 Hours Open (Air-Conditioned & High-Speed Wi-Fi)',
    isOpen: true,
    openedAt: 'Always Open',
    isTemporaryClosed: false,
  },
  {
    id: 'fac-5',
    facilityName: 'Indoor Common Room & Table Tennis Hall',
    standardTimings: '04:00 PM - 10:00 PM',
    isOpen: false,
    closedAt: 'Opens at 04:00 PM',
    isTemporaryClosed: false,
  },
  {
    id: 'fac-6',
    facilityName: 'Nilgiri Main Security Gate & Turnstile',
    standardTimings: 'Open: 06:00 AM | Strict Lock: 09:30 PM',
    isOpen: true,
    openedAt: '06:00 AM',
    isTemporaryClosed: false,
  },
];

export const INITIAL_WARDEN_LEAVES: WardenLeave[] = [
  {
    id: 'wl-1',
    leaveType: 'DUTY',
    startDate: '2026-09-18',
    endDate: '2026-09-19',
    days: 2,
    reason: 'Representing REC Autonomous at BPUT Inter-College Student Affairs & Welfare Summit',
    substituteWarden: 'Prof. Ramesh Chandra Dash (Chief Warden)',
    status: 'APPROVED',
  },
];

export const INITIAL_HOSTEL_STAFF: HostelStaff[] = [
  {
    id: 'stf-1',
    name: 'Bikash Mohapatra',
    role: 'ASST_WARDEN',
    phone: '+91 94370 88220',
    shift: 'Night Duty (08:00 PM - 08:00 AM)',
    status: 'ON_DUTY',
    currentTask: 'Roll-call audit and gate turnstile sync check',
  },
  {
    id: 'stf-2',
    name: 'Niranjan Nayak',
    role: 'CARETAKER',
    phone: '+91 94370 88221',
    shift: 'General Shift (08:00 AM - 05:00 PM)',
    status: 'ON_DUTY',
    currentTask: 'Room change inventory verification for Block A',
  },
  {
    id: 'stf-3',
    name: 'Mahendra Singh',
    role: 'PLUMBER',
    phone: '+91 94370 12045',
    shift: 'Emergency On-Call',
    status: 'ON_DUTY',
    currentTask: 'Repairing 3rd floor washroom tap leak (Ticket #0899)',
  },
  {
    id: 'stf-4',
    name: 'Suresh Kumar',
    role: 'ELECTRICIAN',
    phone: '+91 94370 12044',
    shift: 'Morning Shift (06:00 AM - 02:00 PM)',
    status: 'ON_DUTY',
    currentTask: 'Checking corridor solar inverter connections',
  },
  {
    id: 'stf-5',
    name: 'Basanta Barik',
    role: 'HEAD_COOK',
    phone: '+91 94370 99112',
    shift: 'Kitchen Shift (05:30 AM - 03:00 PM)',
    status: 'ON_DUTY',
    currentTask: 'Lunch preparation: Dalma, Paneer & Rice',
  },
  {
    id: 'stf-6',
    name: 'Rajesh Kumar (Gate 1)',
    role: 'SECURITY_GUARD',
    phone: '+91 94370 55443',
    shift: 'Day Shift (06:00 AM - 06:00 PM)',
    status: 'ON_DUTY',
    currentTask: 'Gate pass barcode scanner & visitor ID verification',
  },
];

export const INITIAL_LEAVE_REQUESTS: LeaveRequestItem[] = [
  {
    id: 'leave-101',
    leaveNumber: 'LV-2026-0042',
    studentId: 'REC-2023-CS042',
    studentName: 'Subham Pradhan',
    photoUrl: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Subham&backgroundColor=b6e3f4',
    hostelName: 'Nilgiri Boys Hostel',
    blockName: 'Nilgiri Block A',
    roomNumber: 'A-204',
    leaveType: 'Home Visit',
    reason: 'Family Puja and Medical Checkup with Parents in Bhubaneswar',
    destination: 'Plot 42, Green Avenue, Bhubaneswar',
    outDate: '2026-10-06',
    outTime: '10:00 AM',
    returnDate: '2026-10-08',
    returnTime: '06:00 PM',
    submittedAt: 'Today, 08:30 AM',
    status: 'PENDING',
    guardianConsent: 'CONFIRMED',
    guardianName: 'Balakrushna Pradhan',
    guardianPhone: '+91 94370 88990',
    studentPhone: '+91 94380 99881',
  },
  {
    id: 'leave-102',
    leaveNumber: 'LV-2026-0038',
    studentId: 'REC-2023-CS089',
    studentName: 'Aman Verma',
    photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    hostelName: 'Nilgiri Boys Hostel',
    blockName: 'Nilgiri Block A',
    roomNumber: 'A-102',
    leaveType: 'Academic / Conference',
    reason: 'Participating in Smart India Hackathon Regional Round at IIT Bhubaneswar',
    destination: 'IIT Bhubaneswar Argul Campus',
    outDate: '2026-10-07',
    outTime: '07:00 AM',
    returnDate: '2026-10-09',
    returnTime: '08:00 PM',
    submittedAt: 'Yesterday, 04:15 PM',
    status: 'PENDING',
    guardianConsent: 'OTP_VERIFIED',
    guardianName: 'Sunil Verma',
    guardianPhone: '+91 98123 45678',
    studentPhone: '+91 91234 56780',
    supportingDocUrl: 'https://example.com/sih-invitation.pdf',
  },
  {
    id: 'leave-103',
    leaveNumber: 'LV-2026-0029',
    studentId: 'REC-2024-ME014',
    studentName: 'Mithun Sahoo',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    hostelName: 'Nilgiri Boys Hostel',
    blockName: 'Nilgiri Block B',
    roomNumber: 'B-205',
    leaveType: 'Medical Leave',
    reason: 'Dental Surgery & 3 days rest advised by Dental Specialist',
    destination: 'Cuttack Medical Campus',
    outDate: '2026-10-03',
    outTime: '09:00 AM',
    returnDate: '2026-10-06',
    returnTime: '07:00 PM',
    submittedAt: '2026-10-02, 11:20 AM',
    status: 'APPROVED',
    guardianConsent: 'CONFIRMED',
    guardianName: 'Baidhar Sahoo',
    guardianPhone: '+91 70086 61234',
    studentPhone: '+91 70086 69999',
  },
  {
    id: 'leave-104',
    leaveNumber: 'LV-2026-0022',
    studentId: 'REC-2023-EC019',
    studentName: 'Pritam Mohanty',
    photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150',
    hostelName: 'Nilgiri Boys Hostel',
    blockName: 'Nilgiri Block B',
    roomNumber: 'B-108',
    leaveType: 'Festival / Vacation',
    reason: 'Sister marriage ceremony and leave',
    destination: 'Rourkela (Home)',
    outDate: '2026-10-02',
    outTime: '02:00 PM',
    returnDate: '2026-10-04',
    returnTime: '09:00 PM',
    submittedAt: '2026-10-01, 11:30 AM',
    status: 'APPROVED',
    guardianConsent: 'CONFIRMED',
    guardianName: 'Dillip Mohanty',
    guardianPhone: '+91 94370 77123',
    studentPhone: '+91 99370 44556',
  },
];

export const INITIAL_MOVEMENT_RECORDS: StudentMovementRecord[] = [
  {
    id: 'mov-1',
    studentId: 'REC-2023-CS042',
    name: 'Subham Pradhan',
    photoUrl: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Subham&backgroundColor=b6e3f4',
    roomNumber: 'A-204',
    blockName: 'Nilgiri Block A',
    course: 'B.Tech CSE Sem 5',
    status: 'OUTSIDE',
    purpose: 'Home Visit & Study Material Collection',
    destination: 'Bhubaneswar Central / Patia',
    exitTime: 'Today, 10:00 AM',
    expectedReturnTime: 'Today, 06:30 PM',
    phone: '+91 94380 99881',
    guardianPhone: '+91 94370 88990',
    guardianName: 'Balakrushna Pradhan',
    passType: 'DAY_PASS',
  },
  {
    id: 'mov-2',
    studentId: 'REC-2022-EE031',
    name: 'Rohan Jena',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    roomNumber: 'A-301',
    blockName: 'Nilgiri Block A',
    course: 'B.Tech EE Sem 7',
    status: 'OVERDUE',
    purpose: 'Hardware component purchase',
    destination: 'Patia Market Complex',
    exitTime: 'Yesterday, 04:12 PM',
    expectedReturnTime: 'Yesterday, 08:30 PM',
    overdueMinutes: 195,
    phone: '+91 98532 11009',
    guardianPhone: '+91 94371 55667',
    guardianName: 'Kabindra Jena',
    passType: 'DAY_PASS',
  },
  {
    id: 'mov-3',
    studentId: 'REC-2024-ME014',
    name: 'Mithun Sahoo',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    roomNumber: 'B-205',
    blockName: 'Nilgiri Block B',
    course: 'B.Tech ME Sem 3',
    status: 'ON_LEAVE',
    purpose: 'Dental surgery recuperation',
    destination: 'Cuttack Home',
    exitTime: '03 Oct, 09:15 AM',
    expectedReturnTime: '06 Oct, 07:00 PM',
    phone: '+91 70086 69999',
    guardianPhone: '+91 70086 61234',
    guardianName: 'Baidhar Sahoo',
    passType: 'MEDICAL_LEAVE',
  },
  {
    id: 'mov-4',
    studentId: 'REC-2023-CS089',
    name: 'Aman Verma',
    photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    roomNumber: 'A-102',
    blockName: 'Nilgiri Block A',
    course: 'B.Tech CSE Sem 3',
    status: 'PRESENT',
    purpose: 'In Hostel Room (Self-Study)',
    destination: 'Hostel Campus',
    phone: '+91 91234 56780',
    guardianPhone: '+91 98123 45678',
    guardianName: 'Sunil Verma',
  },
  {
    id: 'mov-5',
    studentId: 'REC-2023-EC019',
    name: 'Pritam Mohanty',
    photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150',
    roomNumber: 'B-108',
    blockName: 'Nilgiri Block B',
    course: 'B.Tech ECE Sem 5',
    status: 'EXPECTED_RETURN',
    purpose: 'Department robotics lab experiment',
    destination: 'Academic Block Lab 4',
    exitTime: 'Today, 03:00 PM',
    expectedReturnTime: 'Today, 07:30 PM',
    phone: '+91 99370 44556',
    guardianPhone: '+91 94370 77123',
    guardianName: 'Dillip Mohanty',
    passType: 'LOCAL_OUTING',
  },
];

export const INITIAL_MAINTENANCE_TICKETS: MaintenanceTicketItem[] = [
  {
    id: 'maint-101',
    ticketNumber: 'WO-2026-0104',
    studentName: 'Subham Pradhan',
    studentId: 'REC-2023-CS042',
    roomNumber: 'A-204',
    blockName: 'Nilgiri Block A',
    category: 'PLUMBING',
    title: 'Bathroom Tap Washer & Low Water Pressure',
    description: 'Shower and wash basin taps have severe lime deposit and low flow pressure on 2nd floor.',
    photoUrl: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=300',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    assignedStaffName: 'Mahendra Singh (Lead Plumber)',
    assignedStaffPhone: '+91 94370 12045',
    createdAt: '2026-10-04',
    updatedAt: '2026-10-05',
    slaDueHours: 24,
    isOverdue: false,
  },
  {
    id: 'maint-102',
    ticketNumber: 'WO-2026-0098',
    studentName: 'Rohan Jena',
    studentId: 'REC-2022-EE031',
    roomNumber: 'A-301',
    blockName: 'Nilgiri Block A',
    category: 'ELECTRICAL',
    title: 'Ceiling Fan Regulator Spark & Tube Light Capacitor',
    description: 'Ceiling fan makes humming noise and speed regulator sparks upon switching.',
    priority: 'CRITICAL',
    status: 'ASSIGNED',
    assignedStaffName: 'Suresh Kumar (Electrician)',
    assignedStaffPhone: '+91 94370 12044',
    createdAt: '2026-10-05',
    updatedAt: '2026-10-05',
    slaDueHours: 12,
    isOverdue: false,
  },
  {
    id: 'maint-103',
    ticketNumber: 'WO-2026-0089',
    studentName: 'Aman Verma',
    studentId: 'REC-2023-CS089',
    roomNumber: 'A-102',
    blockName: 'Nilgiri Block A',
    category: 'CIVIL',
    title: 'Window Latch Damaged and Mosquito Mesh Torn',
    description: 'South facing window latch broken. Requires new aluminum latch and mesh patch.',
    priority: 'MEDIUM',
    status: 'OPEN',
    createdAt: '2026-10-05',
    updatedAt: '2026-10-05',
    slaDueHours: 48,
    isOverdue: false,
  },
  {
    id: 'maint-104',
    ticketNumber: 'WO-2026-0072',
    roomNumber: 'Block A Corridor Floor 2',
    blockName: 'Nilgiri Block A',
    category: 'HOUSEKEEPING',
    title: 'Water Cooler Drainage Cleaning & Filter Replacement',
    description: 'Scheduled UV & RO filter replacement and drip tray sanitation.',
    priority: 'LOW',
    status: 'RESOLVED',
    assignedStaffName: 'Niranjan Nayak (Caretaker)',
    assignedStaffPhone: '+91 94370 88221',
    createdAt: '2026-10-02',
    updatedAt: '2026-10-04',
    resolvedAt: '2026-10-04, 03:30 PM',
    slaDueHours: 48,
    isOverdue: false,
  },
];

export const INITIAL_REPORTS: HostelReportItem[] = [
  {
    id: 'rep-1',
    name: 'Hostel Occupancy & Bed Inventory Report',
    category: 'OCCUPANCY',
    description: 'Floor-wise, room-wise and bed allocation breakdown for Nilgiri Block A & B.',
    generatedDate: '05 Oct 2026',
    recordCount: 600,
    status: 'READY',
    format: 'PDF',
  },
  {
    id: 'rep-2',
    name: 'Resident Master Roster & Contact Directory',
    category: 'RESIDENTS',
    description: 'Complete student directory with guardian phone, blood group, department & year.',
    generatedDate: '05 Oct 2026',
    recordCount: 520,
    status: 'READY',
    format: 'CSV',
  },
  {
    id: 'rep-3',
    name: 'Gate Pass & Leave Approvals Audit Report',
    category: 'GATE_PASS',
    description: 'All night leaves, day outings, rejection reasons, and parent consent records.',
    generatedDate: '04 Oct 2026',
    recordCount: 142,
    status: 'READY',
    format: 'PDF',
  },
  {
    id: 'rep-4',
    name: 'Late Returns & Curfew Violations Report',
    category: 'LATE_RETURN',
    description: 'Biometric and turnstile barcode audit of arrivals past 09:30 PM curfew.',
    generatedDate: '05 Oct 2026',
    recordCount: 18,
    status: 'READY',
    format: 'CSV',
  },
  {
    id: 'rep-5',
    name: 'Hostel Complaints & SLA Resolution Metrics',
    category: 'COMPLAINTS',
    description: 'Breakdown of plumbing, electrical, WiFi, and cleanliness complaints with average turnaround time.',
    generatedDate: '05 Oct 2026',
    recordCount: 64,
    status: 'READY',
    format: 'PDF',
  },
  {
    id: 'rep-6',
    name: 'Night Roll Call Attendance Logs',
    category: 'ROLL_CALL',
    description: 'Daily presence, approved passes, leave, and unverified absence percentages.',
    generatedDate: '05 Oct 2026',
    recordCount: 30,
    status: 'READY',
    format: 'PDF',
  },
];

export const HOSTEL_OVERVIEW_DETAILS = {
  name: 'Nilgiri Boys Residence Complex',
  type: 'BOYS',
  block: 'Block A & Block B',
  capacity: 600,
  occupancy: 520,
  availableBeds: 80,
  floorsCount: 4,
  roomsCount: 150,
  wardenName: 'Dr. K.P. Mohapatra',
  wardenPhone: '+91 98610 22345',
  asstWardenName: 'Mr. S.N. Rout',
  asstWardenPhone: '+91 98610 88219',
  adminOffice: 'Ground Floor, Room G-04 (Ext: 104)',
  securityGatePhone: '+91 94370 88214',
  medicalEmergencyPhone: '+91 94370 00108',
  floors: [
    { floor: 1, capacity: 160, occupied: 152, available: 8, rooms: 40, status: '95% Full' },
    { floor: 2, capacity: 160, occupied: 144, available: 16, rooms: 40, status: '90% Full' },
    { floor: 3, capacity: 160, occupied: 140, available: 20, rooms: 40, status: '87.5% Full' },
    { floor: 4, capacity: 120, occupied: 84, available: 36, rooms: 30, status: '70% Full' },
  ],
};
