import {
  SecurityGatePass,
  StudentEntryExitLog,
  SecurityVisitor,
  SecurityVehicle,
  SecurityParcel,
  SecurityIncident,
  SecurityEmergency,
  SecurityLostFound,
  SecurityGateLog,
  SecurityReportItem,
  SecurityOfficerProfile,
} from './types';

export const INITIAL_SECURITY_OFFICER: SecurityOfficerProfile = {
  name: 'Officer Rajesh Kumar',
  badgeId: 'SEC-GATE-042',
  designation: 'Senior Security In-Charge',
  gatePost: 'Main Gate 1 (Turnstiles & Vehicle Barrier)',
  phone: '+91 94370 88214',
  shift: 'Day Shift (08:00 AM - 08:00 PM)',
  emergencyContact: '+91 94370 00108',
  supervisorName: 'Col. A. K. Ray (Chief Security Officer)',
  avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160',
};

export const INITIAL_SECURITY_GATE_PASSES: SecurityGatePass[] = [
  {
    id: 'sec-gp-01',
    passNumber: 'GP-2026-1042',
    studentId: 'CS2023042',
    studentName: 'Subham Pradhan',
    studentRoll: 'REC-2023-CS042',
    photoUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120',
    hostel: 'Nilgiri Residence (Block A)',
    roomNumber: 'A-204',
    phone: '+91 98765 43210',
    guardianPhone: '+91 94370 88990',
    passType: 'DAY_PASS',
    destination: 'College Central Library & Stationary Hub',
    reason: 'Project work printing & reference book collection',
    approvedBy: 'Dr. M. Mohapatra (Warden)',
    validDate: 'Today',
    expectedExitTime: '05:30 PM',
    expectedReturnTime: '09:00 PM (Curfew 09:30 PM)',
    status: 'APPROVED',
    qrToken: 'REC-PASS-SUBHAM-0891',
    parentConsent: 'CONFIRMED',
  },
  {
    id: 'sec-gp-02',
    passNumber: 'GP-2026-1039',
    studentId: 'CS2023089',
    studentName: 'Aman Verma',
    studentRoll: 'REC-2023-CS089',
    photoUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=120',
    hostel: 'Nilgiri Residence (Block A)',
    roomNumber: 'A-102',
    phone: '+91 98610 99881',
    guardianPhone: '+91 94371 44520',
    passType: 'LOCAL_OUTING',
    destination: 'City Market / Pharmacy',
    reason: 'Purchase prescription vitamins & personal care items',
    approvedBy: 'Dr. M. Mohapatra (Warden)',
    validDate: 'Today',
    expectedExitTime: '04:30 PM',
    expectedReturnTime: '08:00 PM',
    actualExitTime: '04:35 PM',
    status: 'OUT',
    qrToken: 'REC-PASS-AMAN-4921',
    parentConsent: 'CONFIRMED',
  },
  {
    id: 'sec-gp-03',
    passNumber: 'GP-2026-1035',
    studentId: 'CS2023015',
    studentName: 'Mithun Sahoo',
    studentRoll: 'REC-2023-CS015',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120',
    hostel: 'Nilgiri Residence (Block B)',
    roomNumber: 'B-205',
    phone: '+91 98532 99881',
    guardianPhone: '+91 94372 11990',
    passType: 'DAY_PASS',
    destination: 'Software Hackathon / Coding Club Lab',
    reason: 'Competitive hackathon preparation at CS Tech Block',
    approvedBy: 'Dr. M. Mohapatra (Warden)',
    validDate: 'Today',
    expectedExitTime: '01:00 PM',
    expectedReturnTime: '07:30 PM',
    actualExitTime: '01:10 PM',
    actualReturnTime: '07:22 PM',
    status: 'RETURNED',
    qrToken: 'REC-PASS-MITHUN-0888',
    parentConsent: 'CONFIRMED',
  },
  {
    id: 'sec-gp-04',
    passNumber: 'GP-2026-0994',
    studentId: 'EE2022031',
    studentName: 'Rohan Jena',
    studentRoll: 'REC-2022-EE031',
    photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120',
    hostel: 'Nilgiri Residence (Block A)',
    roomNumber: 'A-301',
    phone: '+91 98532 11009',
    guardianPhone: '+91 94371 55667',
    passType: 'LOCAL_OUTING',
    destination: 'Town Coaching Center',
    reason: 'GATE preparation offline mock test',
    approvedBy: 'Dr. M. Mohapatra (Warden)',
    validDate: 'Today',
    expectedExitTime: '04:15 PM',
    expectedReturnTime: '09:30 PM (Curfew Limit)',
    actualExitTime: '04:18 PM',
    status: 'OVERDUE',
    qrToken: 'REC-PASS-ROHAN-0885',
    parentConsent: 'CONFIRMED',
  },
  {
    id: 'sec-gp-05',
    passNumber: 'GP-2026-1048',
    studentId: 'CS2023044',
    studentName: 'Pritam Mohanty',
    studentRoll: 'REC-2023-CS044',
    photoUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=120',
    hostel: 'Nilgiri Residence (Block B)',
    roomNumber: 'B-104',
    phone: '+91 94371 99001',
    guardianPhone: '+91 94370 22334',
    passType: 'WEEKEND_PASS',
    destination: 'Home Town (Cuttack)',
    reason: 'Family function & sibling marriage ceremony',
    approvedBy: 'Dr. M. Mohapatra (Warden)',
    validDate: 'Today',
    expectedExitTime: '06:00 PM',
    expectedReturnTime: 'Sunday 08:00 PM',
    status: 'APPROVED',
    qrToken: 'REC-PASS-PRITAM-0442',
    parentConsent: 'CONFIRMED',
  },
];

export const INITIAL_ENTRY_EXIT_LOGS: StudentEntryExitLog[] = [
  {
    id: 'log-101',
    timestamp: '07:22 PM',
    studentId: 'CS2023015',
    studentName: 'Mithun Sahoo',
    rollNumber: 'REC-2023-CS015',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120',
    hostel: 'Nilgiri Residence (Block B)',
    room: 'B-205',
    gate: 'Main Turnstile 2',
    direction: 'ENTRY',
    securityOfficer: 'Officer Rajesh Kumar',
    passId: 'GP-2026-1035',
    status: 'AUTHORIZED',
  },
  {
    id: 'log-102',
    timestamp: '04:35 PM',
    studentId: 'CS2023089',
    studentName: 'Aman Verma',
    rollNumber: 'REC-2023-CS089',
    photoUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=120',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-102',
    gate: 'Main Turnstile 1',
    direction: 'EXIT',
    securityOfficer: 'Officer Rajesh Kumar',
    passId: 'GP-2026-1039',
    status: 'AUTHORIZED',
  },
  {
    id: 'log-103',
    timestamp: '04:18 PM',
    studentId: 'EE2022031',
    studentName: 'Rohan Jena',
    rollNumber: 'REC-2022-EE031',
    photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'A-301',
    gate: 'Main Turnstile 1',
    direction: 'EXIT',
    securityOfficer: 'Officer N. Mohanty',
    passId: 'GP-2026-0994',
    status: 'AUTHORIZED',
  },
  {
    id: 'log-104',
    timestamp: '01:10 PM',
    studentId: 'CS2023015',
    studentName: 'Mithun Sahoo',
    rollNumber: 'REC-2023-CS015',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120',
    hostel: 'Nilgiri Residence (Block B)',
    room: 'B-205',
    gate: 'Main Turnstile 2',
    direction: 'EXIT',
    securityOfficer: 'Officer N. Mohanty',
    passId: 'GP-2026-1035',
    status: 'AUTHORIZED',
  },
];

export const INITIAL_SECURITY_VISITORS: SecurityVisitor[] = [
  {
    id: 'vis-101',
    name: 'Balakrushna Pradhan',
    phone: '+91 94370 88990',
    idType: 'Aadhaar',
    idNumber: 'XXXX-XXXX-8921',
    studentVisited: 'Subham Pradhan',
    studentRoll: 'REC-2023-CS042',
    studentRoom: 'Room A-204 (Nilgiri)',
    purpose: 'Delivering winter clothing & college fee payment documents',
    entryTime: '10:15 AM',
    exitTime: '01:30 PM',
    securityOfficer: 'Officer Rajesh Kumar',
    vehicleNumber: 'OD-02-B-1290',
    status: 'Checked Out',
    passNumber: 'VP-2026-041',
  },
  {
    id: 'vis-102',
    name: 'Sunil Verma',
    phone: '+91 98123 45678',
    idType: 'Driving License',
    idNumber: 'DL-04201100234',
    studentVisited: 'Aman Verma',
    studentRoll: 'REC-2023-CS089',
    studentRoom: 'Room A-102 (Nilgiri)',
    purpose: 'Parental meeting with student before examination cycle',
    entryTime: '03:30 PM',
    securityOfficer: 'Officer Rajesh Kumar',
    vehicleNumber: 'OD-05-AB-7711',
    status: 'Checked In',
    passNumber: 'VP-2026-042',
  },
  {
    id: 'vis-103',
    name: 'Kailash Pattnaik',
    phone: '+91 94373 88102',
    idType: 'Aadhaar',
    idNumber: 'XXXX-XXXX-3312',
    studentVisited: 'Mithun Sahoo',
    studentRoll: 'REC-2023-CS015',
    studentRoom: 'Room B-205 (Nilgiri)',
    purpose: 'Guardian drop-off of semester project hardware kit',
    entryTime: '05:00 PM',
    securityOfficer: 'Officer Rajesh Kumar',
    status: 'Expected',
    passNumber: 'VP-2026-043',
  },
  {
    id: 'vis-104',
    name: 'Unverified Commercial Agent',
    phone: '+91 90000 11223',
    idType: 'Voter ID',
    idNumber: 'VTR-99012',
    studentVisited: 'Debashis Rout',
    studentRoll: 'REC-2023-CS011',
    studentRoom: 'Room A-101',
    purpose: 'Attempted marketing material distribution after visiting hours',
    entryTime: '08:45 PM',
    securityOfficer: 'Officer Rajesh Kumar',
    status: 'Rejected',
  },
];

export const INITIAL_SECURITY_VEHICLES: SecurityVehicle[] = [
  {
    id: 'veh-01',
    plateNumber: 'OD-02-AK-4512',
    vehicleType: 'Sedan Car',
    driverName: 'Prof. Ramesh Sharma',
    driverPhone: '+91 94371 88001',
    ownerType: 'STAFF',
    purpose: 'Faculty Evening Lecture & Lab Supervision',
    entryTime: '08:30 AM',
    gate: 'Main Vehicle Gate',
    securityOfficer: 'Officer Rajesh Kumar',
    status: 'INSIDE',
  },
  {
    id: 'veh-02',
    plateNumber: 'OD-05-AB-7711',
    vehicleType: 'SUV',
    driverName: 'Sunil Verma (Parent)',
    driverPhone: '+91 98123 45678',
    ownerType: 'VISITOR',
    purpose: 'Hostel visitor drop-off (VP-2026-042)',
    entryTime: '03:30 PM',
    gate: 'Main Vehicle Gate',
    securityOfficer: 'Officer Rajesh Kumar',
    status: 'INSIDE',
  },
  {
    id: 'veh-03',
    plateNumber: 'OD-02-X-7741',
    vehicleType: 'Campus Shuttle',
    driverName: 'Prafulla Jena',
    driverPhone: '+91 94370 55441',
    ownerType: 'TRANSIT',
    purpose: 'University campus route shuttle schedule',
    entryTime: '06:00 AM',
    gate: 'South Transit Gate',
    securityOfficer: 'Officer N. Mohanty',
    status: 'INSIDE',
  },
  {
    id: 'veh-04',
    plateNumber: 'OD-02-B-1290',
    vehicleType: 'Two-Wheeler',
    driverName: 'Balakrushna Pradhan',
    driverPhone: '+91 94370 88990',
    ownerType: 'VISITOR',
    purpose: 'Parental visit to Subham Pradhan',
    entryTime: '10:15 AM',
    exitTime: '01:30 PM',
    gate: 'Main Vehicle Gate',
    securityOfficer: 'Officer Rajesh Kumar',
    status: 'EXITED',
  },
];

export const INITIAL_SECURITY_PARCELS: SecurityParcel[] = [
  {
    id: 'pcl-01',
    company: 'Amazon',
    parcelNumber: 'AMZ-IN-889104',
    recipientName: 'Subham Pradhan',
    recipientType: 'STUDENT',
    recipientPhone: '+91 98765 43210',
    roomOrDept: 'Room A-204',
    hostelName: 'Nilgiri Block A',
    entryTime: '11:30 AM',
    status: 'Waiting',
    securityOfficer: 'Officer Rajesh Kumar',
  },
  {
    id: 'pcl-02',
    company: 'Flipkart',
    parcelNumber: 'FK-OD-441290',
    recipientName: 'Aman Verma',
    recipientType: 'STUDENT',
    recipientPhone: '+91 98610 99881',
    roomOrDept: 'Room A-102',
    hostelName: 'Nilgiri Block A',
    entryTime: '01:15 PM',
    collectionTime: '04:10 PM',
    status: 'Collected',
    securityOfficer: 'Officer Rajesh Kumar',
  },
  {
    id: 'pcl-03',
    company: 'BlueDart',
    parcelNumber: 'BD-EXP-99014',
    recipientName: 'Dr. M. Mohapatra (Warden)',
    recipientType: 'STAFF',
    recipientPhone: '+91 94370 88210',
    roomOrDept: 'Hostel Admin Office G-04',
    hostelName: 'Nilgiri Complex',
    entryTime: '02:00 PM',
    status: 'Received',
    securityOfficer: 'Officer Rajesh Kumar',
  },
  {
    id: 'pcl-04',
    company: 'Swiggy/Zomato',
    parcelNumber: 'SWG-FOOD-1182',
    recipientName: 'Mithun Sahoo',
    recipientType: 'STUDENT',
    recipientPhone: '+91 98532 99881',
    roomOrDept: 'Room B-205',
    hostelName: 'Nilgiri Block B',
    entryTime: '07:45 PM',
    status: 'Waiting',
    securityOfficer: 'Officer Rajesh Kumar',
  },
];

export const INITIAL_SECURITY_INCIDENTS: SecurityIncident[] = [
  {
    id: 'inc-01',
    incidentNumber: 'SEC-INC-2026-081',
    date: 'Today',
    time: '08:45 PM',
    location: 'Main Turnstile Gate 1',
    category: 'INVALID_PASS',
    description: 'Commercial agent attempted unauthorized entry using expired visitor badge after 07:00 PM visitor hours.',
    reportedBy: 'Officer Rajesh Kumar',
    status: 'Resolved',
    actionTaken: 'Denied entry at barrier, vehicle turned back, incident logged in security audit ledger.',
  },
  {
    id: 'inc-02',
    incidentNumber: 'SEC-INC-2026-080',
    date: 'Today',
    time: '09:35 PM',
    location: 'Nilgiri Block A Perimeter Barrier',
    category: 'UNAUTHORIZED_ENTRY',
    description: 'Student attempting late entry bypassing turnstiles without QR verification after 09:30 PM curfew.',
    reportedBy: 'Patrol Officer B. Swain',
    status: 'Under Review',
    actionTaken: 'Resident brought to security desk, ID verified, Warden Dr. Mohapatra notified for curfew audit.',
  },
];

export const INITIAL_SECURITY_EMERGENCIES: SecurityEmergency[] = [
  {
    id: 'em-sec-01',
    studentName: 'Subham Pradhan',
    studentRoll: 'REC-2023-CS042',
    studentId: 'CS2023042',
    hostel: 'Nilgiri Residence (Block A)',
    room: 'Room A-204',
    phone: '+91 98765 43210',
    parentPhone: '+91 94370 88990',
    emergencyType: 'MEDICAL',
    timestamp: '10 mins ago',
    locationDetails: '2nd Floor, Room A-204 (Nilgiri Block A)',
    notes: 'Resident triggered Medical SOS button on Student Platform. High fever and acute asthma breathing difficulty.',
    status: 'ACTIVE',
  },
];

export const INITIAL_LOST_FOUND: SecurityLostFound[] = [
  {
    id: 'lf-01',
    itemType: 'FOUND',
    itemName: 'Scientific Calculator (Casio fx-991EX)',
    description: 'Black scientific calculator found on bench near Main Turnstile Gate 1.',
    location: 'Main Turnstile Gate 1',
    date: 'Today',
    time: '03:15 PM',
    reportedBy: 'Turnstile Guard Desk',
    reportedByPhone: '+91 94370 88214',
    status: 'Found',
  },
  {
    id: 'lf-02',
    itemType: 'LOST',
    itemName: 'Student University ID Card',
    description: 'Smart Digital ID card belonging to Pritam Mohanty (REC-2023-CS044).',
    location: 'Library Quad to Nilgiri Path',
    date: 'Today',
    time: '01:30 PM',
    reportedBy: 'Pritam Mohanty',
    reportedByPhone: '+91 94371 99001',
    status: 'Reported',
  },
  {
    id: 'lf-03',
    itemType: 'FOUND',
    itemName: 'Hostel Room Key Bunch with Blue Tag',
    description: '2 brass keys with blue tag stamped "A-204" found at campus pharmacy entrance.',
    location: 'Campus Pharmacy Post',
    date: 'Yesterday',
    time: '06:00 PM',
    reportedBy: 'Pharmacist Desk',
    reportedByPhone: '+91 94370 00108',
    status: 'Claimed',
    claimedBy: 'Subham Pradhan (Verified)',
    claimedDate: 'Today, 09:30 AM',
  },
];

export const INITIAL_GATE_LOGS: SecurityGateLog[] = [
  {
    id: 'gl-01',
    timestamp: '07:22 PM',
    personName: 'Mithun Sahoo (Student)',
    category: 'STUDENT',
    direction: 'ENTRY',
    gate: 'Main Turnstile 2',
    passOrVisitorId: 'GP-2026-1035',
    securityOfficer: 'Officer Rajesh Kumar',
    status: 'GRANTED',
  },
  {
    id: 'gl-02',
    timestamp: '05:00 PM',
    personName: 'OD-05-AB-7711 (Visitor SUV)',
    category: 'VEHICLE',
    direction: 'ENTRY',
    gate: 'Main Vehicle Barrier',
    passOrVisitorId: 'VP-2026-042',
    securityOfficer: 'Officer Rajesh Kumar',
    status: 'GRANTED',
  },
  {
    id: 'gl-03',
    timestamp: '04:35 PM',
    personName: 'Aman Verma (Student)',
    category: 'STUDENT',
    direction: 'EXIT',
    gate: 'Main Turnstile 1',
    passOrVisitorId: 'GP-2026-1039',
    securityOfficer: 'Officer Rajesh Kumar',
    status: 'GRANTED',
  },
  {
    id: 'gl-04',
    timestamp: '04:18 PM',
    personName: 'Rohan Jena (Student)',
    category: 'STUDENT',
    direction: 'EXIT',
    gate: 'Main Turnstile 1',
    passOrVisitorId: 'GP-2026-0994',
    securityOfficer: 'Officer N. Mohanty',
    status: 'GRANTED',
  },
  {
    id: 'gl-05',
    timestamp: '01:30 PM',
    personName: 'Balakrushna Pradhan (Visitor)',
    category: 'VISITOR',
    direction: 'EXIT',
    gate: 'Main Gate 1',
    passOrVisitorId: 'VP-2026-041',
    securityOfficer: 'Officer Rajesh Kumar',
    status: 'GRANTED',
  },
  {
    id: 'gl-06',
    timestamp: '08:45 PM',
    personName: 'Unverified Delivery Courier',
    category: 'VISITOR',
    direction: 'ENTRY',
    gate: 'Main Gate 1',
    passOrVisitorId: 'N/A',
    securityOfficer: 'Officer Rajesh Kumar',
    status: 'DENIED',
  },
];

export const INITIAL_SECURITY_REPORTS: SecurityReportItem[] = [
  {
    id: 'rep-sec-01',
    name: "Daily Student Entry Register",
    category: 'DAILY_ENTRY',
    recordCount: 48,
    description: 'Official record of all student gate entries verified via QR turnstile scan.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-sec-02',
    name: "Daily Student Exit Register",
    category: 'DAILY_EXIT',
    recordCount: 52,
    description: 'Turnstile verified campus departures with destination and Warden pass ID.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-sec-03',
    name: 'Gate Pass Clearance Audit',
    category: 'GATE_PASS',
    recordCount: 38,
    description: 'Summary of day passes, local outings, weekend passes, and warden approvals.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-sec-04',
    name: 'Visitor Entry & Exit Register',
    category: 'VISITORS',
    recordCount: 14,
    description: 'ID-verified guest passes, visited student rooms, vehicle plates, and timings.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-sec-05',
    name: 'Curfew & Overdue Returns Report',
    category: 'OVERDUE_RETURNS',
    recordCount: 3,
    description: 'Students failing to report back before 09:30 PM curfew with elapsed durations.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-sec-06',
    name: 'Vehicle Entry / Exit Audit Log',
    category: 'VEHICLES',
    recordCount: 34,
    description: 'Plate numbers, driver identifications, vehicle categories, and bay assignments.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-sec-07',
    name: 'Security Incident & Breach Register',
    category: 'INCIDENTS',
    recordCount: 2,
    description: 'Documented gate incidents, unauthorized entry attempts, and corrective actions.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-sec-08',
    name: 'Emergency SOS Response Audit',
    category: 'EMERGENCY',
    recordCount: 1,
    description: 'Distress triggers, ambulance dispatch response times, and containment logs.',
    generatedDate: 'Today',
    format: 'CSV',
  },
  {
    id: 'rep-sec-09',
    name: 'Turnstile & Gate Activity Consolidated Log',
    category: 'GATE_ACTIVITY',
    recordCount: 156,
    description: '24-hour audit of turnstile barrier operations, manual overrides, and visitor slips.',
    generatedDate: 'Today',
    format: 'CSV',
  },
];
