import {
  Course,
  ScheduleSlot,
  Student,
  AttendanceRecord,
  Material,
  Assignment,
  ExamDuty,
  MarksEntry,
  StudentRequest,
  AcademicIssue,
  CollegeNotice,
  CalendarEvent,
  FacultyLeave,
  ResearchPublication,
  EducationRecord,
  LearningResource,
} from './types';

export const INITIAL_COURSES: Course[] = [
  {
    code: 'CS-401',
    name: 'Design & Analysis of Algorithms',
    batch: 'B.Tech CSE - 5th Sem (Sec A)',
    semester: '5th Semester',
    credits: 4,
    studentsCount: 68,
    progressPct: 67,
    lecturesCompleted: 28,
    totalLectures: 42,
    syllabusUnits: [
      {
        unit: 'Unit 1',
        title: 'Asymptotic Complexity & Recurrences',
        topics: ['Big-O, Omega, Theta', 'Master Theorem', 'Substitution Method', 'Recursion Trees'],
        hours: 10,
      },
      {
        unit: 'Unit 2',
        title: 'Divide & Conquer and Greedy Method',
        topics: ['Merge Sort', 'Quick Sort', 'Fractional Knapsack', 'Huffman Coding', 'MST Prim & Kruskal'],
        hours: 12,
      },
      {
        unit: 'Unit 3',
        title: 'Dynamic Programming & Graph Algorithms',
        topics: ['0/1 Knapsack', 'LCS', 'Matrix Chain Multiplication', 'Bellman-Ford', 'Floyd-Warshall'],
        hours: 12,
      },
      {
        unit: 'Unit 4',
        title: 'NP-Completeness & Approximation',
        topics: ['P vs NP', 'NP-Hard & NP-Complete', 'Vertex Cover', 'Traveling Salesperson Problem'],
        hours: 8,
      },
    ],
  },
  {
    code: 'CS-401L',
    name: 'Algorithms Laboratory & Competitive Coding',
    batch: 'B.Tech CSE - 5th Sem (Sec A - Batch 1 & 2)',
    semester: '5th Semester',
    credits: 2,
    studentsCount: 68,
    progressPct: 75,
    lecturesCompleted: 18,
    totalLectures: 24,
    syllabusUnits: [
      {
        unit: 'Lab Module 1',
        title: 'Sorting & Empirical Time Complexity Analysis',
        topics: ['Execution benchmark scripts', 'Worst case input generation in C++17'],
        hours: 8,
      },
      {
        unit: 'Lab Module 2',
        title: 'Graph Traversal & Greedy MST Simulations',
        topics: ['BFS/DFS applications', 'Disjoint Set Union (DSU) Kruskal implementation'],
        hours: 8,
      },
      {
        unit: 'Lab Module 3',
        title: 'Dynamic Programming Memoization Tables',
        topics: ['Grid DP', 'Interval DP', 'State compression optimizations'],
        hours: 8,
      },
    ],
  },
  {
    code: 'CS-502',
    name: 'Cloud Computing & Distributed Microservices',
    batch: 'B.Tech CSE - 7th Sem (Professional Elective)',
    semester: '7th Semester',
    credits: 3,
    studentsCount: 52,
    progressPct: 60,
    lecturesCompleted: 21,
    totalLectures: 35,
    syllabusUnits: [
      {
        unit: 'Unit 1',
        title: 'Virtualization & Hypervisor Architectures',
        topics: ['Type-1 vs Type-2', 'Containerization with Docker & Podman', 'KVM & QEMU'],
        hours: 10,
      },
      {
        unit: 'Unit 2',
        title: 'Cloud Service Models & Scalability',
        topics: ['IaaS, PaaS, SaaS, FaaS', 'Horizontal vs Vertical autoscaling', 'Load balancing'],
        hours: 12,
      },
      {
        unit: 'Unit 3',
        title: 'Microservices, Kafka & Kubernetes',
        topics: ['Event-driven systems', 'K8s Pods, Deployments & Ingress', 'Service mesh'],
        hours: 13,
      },
    ],
  },
];

export const INITIAL_SCHEDULE: ScheduleSlot[] = [
  {
    id: 'sch-1',
    code: 'CS-401',
    name: 'Algorithms Theory (Bellman-Ford DP)',
    batch: 'CSE Year 3 (Sec A)',
    time: '09:00 AM - 10:00 AM',
    room: 'Hall 302',
    day: 'Monday',
    status: 'COMPLETED',
  },
  {
    id: 'sch-2',
    code: 'CS-401L',
    name: 'Algorithms Lab (Batch 1)',
    batch: 'CSE Year 3 (Sec A)',
    time: '11:30 AM - 01:30 PM',
    room: 'Coding Lab 1',
    day: 'Monday',
    status: 'SCHEDULED',
  },
  {
    id: 'sch-3',
    code: 'CS-502',
    name: 'Cloud Computing (K8s Architecture)',
    batch: 'CSE Year 4 (Elective)',
    time: '02:30 PM - 03:30 PM',
    room: 'Seminar Hall 2',
    day: 'Monday',
    status: 'SCHEDULED',
  },
  {
    id: 'sch-4',
    code: 'CS-401',
    name: 'Algorithms Theory (Floyd-Warshall)',
    batch: 'CSE Year 3 (Sec A)',
    time: '10:00 AM - 11:00 AM',
    room: 'Hall 302',
    day: 'Tuesday',
    status: 'SCHEDULED',
  },
  {
    id: 'sch-5',
    code: 'CS-401L',
    name: 'Algorithms Lab (Batch 2)',
    batch: 'CSE Year 3 (Sec A)',
    time: '02:00 PM - 04:00 PM',
    room: 'Coding Lab 1',
    day: 'Tuesday',
    status: 'SCHEDULED',
  },
  {
    id: 'sch-6',
    code: 'CS-502',
    name: 'Cloud Computing (Kafka Streaming)',
    batch: 'CSE Year 4 (Elective)',
    time: '09:00 AM - 10:00 AM',
    room: 'Seminar Hall 2',
    day: 'Wednesday',
    status: 'SCHEDULED',
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'st-1',
    roll: 'REC-2023-CS042',
    name: 'Subham Pradhan',
    batch: 'CSE Year 3 (Sec A)',
    cgpa: 9.12,
    attendance: 94.5,
    hostel: 'Hostel A',
    room: 'A-204',
    phone: '+91 98765 11001',
    parentPhone: '+91 98000 11111',
    email: 'subham.pradhan@rec.ac.in',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120',
    status: 'Distinction Scholar',
    isMentee: true,
    remarks: ['Excellent understanding of algorithms', 'Participating in Smart India Hackathon'],
    counsellingNotes: [
      {
        id: 'cn-1',
        date: '28 Sep 2026',
        category: 'ACADEMIC',
        note: 'Discussed SIH AI prototype architecture and research paper publication.',
        followUpDate: '15 Oct 2026',
      },
    ],
  },
  {
    id: 'st-2',
    roll: 'REC-2023-CS001',
    name: 'Aarav Sharma',
    batch: 'CSE Year 3 (Sec A)',
    cgpa: 8.45,
    attendance: 72.0, // Critical shortage (<75%)
    hostel: 'Hostel A',
    room: 'A-102',
    phone: '+91 98765 11003',
    parentPhone: '+91 98000 22001',
    email: 'aarav.sharma@rec.ac.in',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=120',
    status: 'Attendance Shortage Warning (<75%)',
    isMentee: true,
    remarks: ['Missed 6 classes due to fever in September', 'Needs to attend remedial tutorial'],
    counsellingNotes: [
      {
        id: 'cn-2',
        date: '02 Oct 2026',
        category: 'ATTENDANCE',
        note: 'Informed student that attendance is 72%. Advised 100% attendance in October to avoid exam debarment.',
      },
    ],
  },
  {
    id: 'st-3',
    roll: 'REC-2023-CS002',
    name: 'Aditi Mohapatra',
    batch: 'CSE Year 3 (Sec A)',
    cgpa: 8.85,
    attendance: 88.0,
    hostel: 'Gargi Hall',
    room: 'G-305',
    phone: '+91 98765 11002',
    parentPhone: '+91 98000 22002',
    email: 'aditi.mohapatra@rec.ac.in',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120',
    status: 'Active',
    isMentee: true,
    remarks: ['Consistent in coding lab submissions', 'Lead organizer of REC Coding Club'],
  },
  {
    id: 'st-4',
    roll: 'REC-2023-CS004',
    name: 'Ananya Sen',
    batch: 'CSE Year 3 (Sec A)',
    cgpa: 7.42,
    attendance: 71.5, // Critical (<75%)
    hostel: 'Gargi Hall',
    room: 'G-110',
    phone: '+91 98765 11004',
    parentPhone: '+91 98000 22004',
    email: 'ananya.sen@rec.ac.in',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120',
    status: 'Attendance Shortage Warning (<75%)',
    isMentee: false,
    remarks: ['Medical prescription submitted for 3 days'],
  },
  {
    id: 'st-5',
    roll: 'REC-2023-CS005',
    name: 'Bhavna Rath',
    batch: 'CSE Year 3 (Sec A)',
    cgpa: 8.64,
    attendance: 89.2,
    hostel: 'Gargi Hall',
    room: 'G-208',
    phone: '+91 98765 11005',
    parentPhone: '+91 98000 22005',
    email: 'bhavna.rath@rec.ac.in',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120',
    status: 'Active',
    isMentee: true,
  },
  {
    id: 'st-6',
    roll: 'REC-2023-CS006',
    name: 'Chirag Pradhan',
    batch: 'CSE Year 3 (Sec A)',
    cgpa: 7.95,
    attendance: 82.0,
    hostel: 'Hostel B',
    room: 'B-214',
    phone: '+91 98765 11006',
    parentPhone: '+91 98000 22006',
    email: 'chirag.pradhan@rec.ac.in',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120',
    status: 'Active',
    isMentee: true,
  },
  {
    id: 'st-7',
    roll: 'REC-2022-CS018',
    name: 'Isha Das',
    batch: 'CSE Year 4 (Elective)',
    cgpa: 9.35,
    attendance: 96.0,
    hostel: 'Gargi Hall',
    room: 'G-401',
    phone: '+91 98765 11008',
    parentPhone: '+91 98000 22008',
    email: 'isha.das@rec.ac.in',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=120',
    status: 'Distinction Scholar',
    isMentee: true,
  },
  {
    id: 'st-8',
    roll: 'REC-2022-CS022',
    name: 'Karan Mishra',
    batch: 'CSE Year 4 (Elective)',
    cgpa: 6.98,
    attendance: 68.2, // Critical (<75%)
    hostel: 'Hostel A',
    room: 'A-312',
    phone: '+91 98765 11009',
    parentPhone: '+91 98000 22009',
    email: 'karan.mishra@rec.ac.in',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120',
    status: 'Attendance Shortage Warning (<75%)',
    isMentee: false,
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = INITIAL_STUDENTS.map((s) => ({
  roll: s.roll,
  name: s.name,
  batch: s.batch,
  status: s.attendance < 75 ? 'ABSENT' : 'PRESENT',
  isMedicalApproved: s.roll === 'REC-2023-CS004',
  note: s.roll === 'REC-2023-CS004' ? 'Approved Medical Exemption by Dean' : '',
  auditHistory: [
    {
      date: '04 Oct 2026, 09:45 AM',
      previousStatus: 'ABSENT',
      newStatus: 'ON_LEAVE',
      reason: 'Medical prescription verified from campus clinic',
      updatedBy: 'Prof. Sujata Panda',
    },
  ],
}));

export const INITIAL_MATERIALS: Material[] = [
  {
    id: 'mat-1',
    title: 'Unit 2: Divide & Conquer and Master Theorem Derivations',
    course: 'CS-401 Algorithms',
    type: 'PDF',
    size: '3.4 MB',
    date: '02 Oct 2026',
    downloads: 138,
    views: 184,
    visibility: 'ALL',
    url: '#',
  },
  {
    id: 'mat-2',
    title: 'Unit 3: Dynamic Programming Bellman-Ford Negative Cycle Proofs',
    course: 'CS-401 Algorithms',
    type: 'SLIDES',
    size: '7.8 MB',
    date: '29 Sep 2026',
    downloads: 112,
    views: 145,
    visibility: 'SEC_A',
    url: '#',
  },
  {
    id: 'mat-3',
    title: 'Lab Sheet 4: DSU & Kruskal Algorithm in C++ STL with Test Cases',
    course: 'CS-401L Algorithms Lab',
    type: 'LAB_MANUAL',
    size: '1.2 MB',
    date: '25 Sep 2026',
    downloads: 68,
    views: 92,
    visibility: 'SEC_A',
    url: '#',
  },
  {
    id: 'mat-4',
    title: 'REC Autonomous Mid-Semester 2024 Question Paper & Model Key',
    course: 'CS-401 Algorithms',
    type: 'PYQ',
    size: '1.8 MB',
    date: '15 Sep 2026',
    downloads: 210,
    views: 340,
    visibility: 'ALL',
    url: '#',
    isPYQ: true,
    year: '2024 Mid-Sem',
  },
  {
    id: 'mat-5',
    title: 'BPUT End-Semester 2023 Autonomous Examination Solved Paper',
    course: 'CS-401 Algorithms',
    type: 'PYQ',
    size: '2.5 MB',
    date: '10 Sep 2026',
    downloads: 265,
    views: 410,
    visibility: 'ALL',
    url: '#',
    isPYQ: true,
    year: '2023 End-Sem',
  },
  {
    id: 'mat-6',
    title: 'Kubernetes Pod Networking & Kafka Streaming Handout',
    course: 'CS-502 Cloud Computing',
    type: 'PDF',
    size: '4.1 MB',
    date: '18 Sep 2026',
    downloads: 48,
    views: 74,
    visibility: 'SEC_B',
    url: '#',
  },
];

export const INITIAL_ASSIGNMENTS: Assignment[] = [
  {
    id: 'asg-1',
    title: 'Assignment 2: DP Matrix Chain Multiplication & 0/1 Knapsack',
    course: 'CS-401 Algorithms',
    batch: 'CSE Year 3 (Sec A)',
    deadline: '08 Oct 2026, 11:59 PM',
    maxMarks: 50,
    submittedCount: 62,
    totalCount: 68,
    status: 'ACTIVE',
    submissions: [
      {
        id: 'sub-1',
        studentRoll: 'REC-2023-CS042',
        studentName: 'Subham Pradhan',
        submittedAt: '04 Oct, 04:30 PM',
        isLate: false,
        marks: 48,
        feedback: 'Flawless optimal substructure proofs and test suite.',
        fileUrl: '#',
        similarityScore: 4,
        duplicateWarning: false,
      },
      {
        id: 'sub-2',
        studentRoll: 'REC-2023-CS002',
        studentName: 'Aditi Mohapatra',
        submittedAt: '04 Oct, 07:15 PM',
        isLate: false,
        marks: 46,
        feedback: 'Well documented recursion tree diagrams.',
        fileUrl: '#',
        similarityScore: 8,
        duplicateWarning: false,
      },
      {
        id: 'sub-3',
        studentRoll: 'REC-2023-CS004',
        studentName: 'Ananya Sen',
        submittedAt: '05 Oct, 01:10 AM',
        isLate: true,
        marks: 38,
        feedback: 'Late submission. Memoization array indexing has edge case flaw.',
        fileUrl: '#',
        similarityScore: 82,
        duplicateWarning: true,
      },
      {
        id: 'sub-4',
        studentRoll: 'REC-2023-CS006',
        studentName: 'Chirag Pradhan',
        submittedAt: '04 Oct, 11:45 PM',
        isLate: false,
        marks: 40,
        feedback: 'Good explanation of space complexity optimization.',
        fileUrl: '#',
        similarityScore: 82,
        duplicateWarning: true,
      },
    ],
  },
  {
    id: 'asg-2',
    title: 'Lab Evaluation 2: Bellman-Ford Negative Cycle Detection in C++',
    course: 'CS-401L Algorithms Lab',
    batch: 'CSE Year 3 (Sec A)',
    deadline: '10 Oct 2026, 05:00 PM',
    maxMarks: 30,
    submittedCount: 54,
    totalCount: 68,
    status: 'ACTIVE',
    submissions: [],
  },
  {
    id: 'asg-3',
    title: 'Assignment 1: Microservice Containerization with Docker Compose',
    course: 'CS-502 Cloud Computing',
    batch: 'CSE Year 4 (Elective)',
    deadline: '30 Sep 2026',
    maxMarks: 50,
    submittedCount: 52,
    totalCount: 52,
    status: 'EVALUATED',
    submissions: [],
  },
];

export const INITIAL_EXAM_DUTIES: ExamDuty[] = [
  {
    id: 'ex-1',
    examName: 'REC Autonomous Mid-Semester Exam (Autumn 2026)',
    courseCode: 'CS-401',
    courseName: 'Design & Analysis of Algorithms',
    date: '12 Oct 2026',
    time: '10:00 AM - 01:00 PM',
    hall: 'Block 1 - Hall 302 (Capacity: 70)',
    role: 'CHIEF_INVIGILATOR',
    partnerFaculty: 'Dr. Debabrata Swain (Dept. of CSE)',
    status: 'UPCOMING',
  },
  {
    id: 'ex-2',
    examName: 'REC Autonomous Mid-Semester Exam (Autumn 2026)',
    courseCode: 'EC-302',
    courseName: 'Digital Signal Processing (Cross-Dept Invigilation)',
    date: '14 Oct 2026',
    time: '02:00 PM - 05:00 PM',
    hall: 'Block 2 - Hall 204 (Capacity: 60)',
    role: 'ASSISTANT_INVIGILATOR',
    partnerFaculty: 'Prof. Rajesh Verma (Dept. of ECE)',
    status: 'UPCOMING',
  },
];

export const INITIAL_MARKS_ENTRIES: MarksEntry[] = INITIAL_STUDENTS.map((s, idx) => ({
  studentRoll: s.roll,
  studentName: s.name,
  midSemMarks: Math.min(30, Math.round(s.cgpa * 3.1)),
  assignmentMarks: Math.min(20, Math.round(s.cgpa * 2.1)),
  totalInternal: Math.min(50, Math.round(s.cgpa * 3.1 + s.cgpa * 2.1)),
  maxInternal: 50,
  status: idx < 4 ? 'SUBMITTED' : 'DRAFT',
}));

export const INITIAL_STUDENT_REQUESTS: StudentRequest[] = [
  {
    id: 'req-1',
    studentName: 'Subham Pradhan',
    roll: 'REC-2023-CS042',
    type: 'LOR',
    title: 'Letter of Recommendation (LOR) for MITACS Canada Research Internship',
    details: 'Applying for Globalink Research Internship 2027 in Algorithmic AI. Requesting recommendation letter highlighting algorithms coursework and coding contest performance.',
    appliedDate: '03 Oct 2026',
    ageingDays: 2,
    status: 'IN_PROGRESS',
    facultyRemark: 'Drafted and endorsed on REC Autonomous letterhead. Pending final dean seal.',
  },
  {
    id: 'req-2',
    studentName: 'Aditi Mohapatra',
    roll: 'REC-2023-CS002',
    type: 'MEDICAL_LEAVE',
    title: 'Academic On-Duty Leave Verification for Smart India Hackathon Grand Finale',
    details: 'Representing REC Autonomous in SIH 2026 Grand Finale at IIT Bhubaneswar from 08 Oct to 11 Oct.',
    appliedDate: '04 Oct 2026',
    ageingDays: 1,
    status: 'APPROVED',
    facultyRemark: 'Verified official finalist invitation letter. On-Duty attendance granted.',
  },
  {
    id: 'req-3',
    studentName: 'Chirag Pradhan',
    roll: 'REC-2023-CS006',
    type: 'ELECTIVE_CHANGE',
    title: 'Elective Track Alignment Request: Cloud Computing & Distributed Systems',
    details: 'Requesting permission to audit CS-502 lab components for capstone project.',
    appliedDate: '30 Sep 2026',
    ageingDays: 5,
    status: 'SUBMITTED',
    facultyRemark: '',
  },
  {
    id: 'req-4',
    studentName: 'Ananya Sen',
    roll: 'REC-2023-CS004',
    type: 'BONAFIDE',
    title: 'Bonafide Endorsement for BPUT Academic Conference Registration',
    details: 'Presenting research poster on Graph Neural Networks at BPUT TechFest.',
    appliedDate: '01 Oct 2026',
    ageingDays: 4,
    status: 'APPROVED',
    facultyRemark: 'Recommended and forwarded to Principal Desk.',
  },
];

export const INITIAL_ACADEMIC_ISSUES: AcademicIssue[] = [
  {
    id: 'iss-1',
    category: 'PROJECTOR',
    location: 'Academic Block 1 • Hall 302',
    title: 'Overhead Projector HDMI Port flickering during CS-401 lecture',
    description: 'During morning 9 AM lecture, HDMI port drops video signal every 5 minutes. Audio buzz is audible.',
    photoUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400',
    priority: 'URGENT',
    reportedDate: '04 Oct 2026, 10:15 AM',
    status: 'IN_PROGRESS',
    resolutionNote: 'AV Technician assigned. Replacing ceiling HDMI transceiver cable.',
    facultyConfirmedFixed: false,
  },
  {
    id: 'iss-2',
    category: 'SOFTWARE',
    location: 'Coding Lab 1 • Workstations 12 to 20',
    title: 'GCC 13 Compiler Environment Variable path missing in Ubuntu dual boot',
    description: 'Students unable to compile C++17 STL code during Tuesday lab session.',
    photoUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400',
    priority: 'NORMAL',
    reportedDate: '03 Oct 2026, 02:40 PM',
    status: 'RESOLVED',
    resolutionNote: 'Lab assistant updated /etc/environment and pushed image to all 30 PCs.',
    facultyConfirmedFixed: true,
  },
  {
    id: 'iss-3',
    category: 'WIFI',
    location: 'Faculty Cabin Wing • Block 2 Floor 3',
    title: 'REC-Faculty-5G Wi-Fi access point frequent authentication drops',
    description: 'Faculty laptops disconnecting during online attendance submission and BPUT portal uploads.',
    priority: 'URGENT',
    reportedDate: '02 Oct 2026, 11:00 AM',
    status: 'IN_PROGRESS',
    resolutionNote: 'Network team rebooting Cisco switch on 3rd floor rack.',
    facultyConfirmedFixed: false,
  },
];

export const INITIAL_NOTICES: CollegeNotice[] = [
  {
    id: 'not-1',
    title: 'REC Autonomous Mid-Semester Question Paper Submission (Deadline: Oct 08)',
    date: '04 Oct 2026',
    category: 'REC_AUTONOMOUS',
    isPinned: true,
    isActionRequired: true,
    deadline: '08 Oct 2026, 05:00 PM',
    audience: 'All Faculty & Course In-Charges',
    content: 'All faculty members teaching odd semester courses (3rd, 5th, 7th Sem) must submit 2 confidential question paper sets with detailed marking schemes directly through the Faculty Portal QP Upload Vault.',
    read: false,
    actionCompleted: false,
  },
  {
    id: 'not-2',
    title: 'BPUT University Circular on Autonomous Curriculum Revision & AICTE Framework',
    date: '03 Oct 2026',
    category: 'BPUT',
    isPinned: true,
    isActionRequired: false,
    audience: 'Autonomous Engineering Colleges in Odisha',
    content: 'BPUT guidelines for inclusion of Multidisciplinary Minors and Industry Micro-Credentials in 2026-27 autonomous curriculum structure.',
    read: true,
  },
  {
    id: 'not-3',
    title: 'Department of CSE: Board of Studies Meeting regarding Electives',
    date: '01 Oct 2026',
    category: 'CSE_DEPT',
    isPinned: false,
    isActionRequired: true,
    deadline: '15 Oct 2026',
    audience: 'Department Faculty & External Experts',
    content: 'Meeting to review syllabus revisions for Cloud Computing, Generative AI, and Quantum Algorithms in Room 314 at 03:00 PM.',
    read: false,
    actionCompleted: false,
  },
];

export const INITIAL_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 'cal-1',
    title: 'REC Autonomous Mid-Semester Examinations Begin',
    date: '12 Oct 2026',
    time: '10:00 AM - 01:00 PM',
    category: 'EXAM',
    description: 'Odd Semester Mid-Term Theory exams across all engineering departments.',
    location: 'Exam Block & Central Halls',
  },
  {
    id: 'cal-2',
    title: 'Durga Puja & Dussehra Vacation (College Closed)',
    date: '20 Oct - 25 Oct 2026',
    time: 'All Day',
    category: 'HOLIDAY',
    description: 'Annual institutional autumn festival break.',
  },
  {
    id: 'cal-3',
    title: 'Faculty Development Program (FDP) on High-Performance Computing',
    date: '28 Oct 2026',
    time: '10:00 AM - 04:30 PM',
    category: 'FDP',
    description: 'AICTE-ATAL sponsored 5-day National Workshop organized by REC CSE Dept.',
    location: 'Main Auditorium',
  },
  {
    id: 'cal-4',
    title: 'HOD Academic Review & Monthly Attendance Audit',
    date: '30 Oct 2026',
    time: '03:30 PM - 05:00 PM',
    category: 'MEETING',
    description: 'Review of course coverage, short attendance warnings dispatched, and student feedback analysis.',
    location: 'Conference Room 1',
  },
];

export const INITIAL_FACULTY_LEAVES: FacultyLeave[] = [
  {
    id: 'flv-1',
    category: 'Duty Leave (OD)',
    fromDate: '2026-09-18',
    toDate: '2026-09-20',
    days: 3,
    reason: 'Paper presentation at IEEE Eastern Regional Conference at IIT Kharagpur',
    substituteFaculty: 'Prof. Rajesh Verma',
    status: 'APPROVED',
    appliedDate: '10 Sep 2026',
  },
  {
    id: 'flv-2',
    category: 'Casual Leave (CL)',
    fromDate: '2026-08-14',
    toDate: '2026-08-14',
    days: 1,
    reason: 'Personal family matter',
    substituteFaculty: 'Dr. Debabrata Swain',
    status: 'APPROVED',
    appliedDate: '12 Aug 2026',
  },
];

export const INITIAL_PUBLICATIONS: ResearchPublication[] = [
  {
    id: 'pub-1',
    title: 'Federated Optimization in Resource-Constrained Edge Clusters',
    journalOrConf: 'IEEE Transactions on Cloud Computing',
    year: 2025,
    doi: '10.1109/TCC.2025.3214567',
    type: 'JOURNAL',
    citations: 24,
  },
  {
    id: 'pub-2',
    title: 'Distributed Graph Decomposition for Large-Scale Knowledge Graphs',
    journalOrConf: 'ACM SIGMOD International Conference on Data Engineering',
    year: 2024,
    doi: '10.1145/3626246.3653378',
    type: 'CONFERENCE',
    citations: 38,
  },
  {
    id: 'pub-3',
    title: 'Smart Campus Automated Energy Management System using IoT & Edge ML',
    journalOrConf: 'Indian Patent Office (Application No: 202431089712)',
    year: 2024,
    type: 'PATENT',
  },
];

export const INITIAL_EDUCATION: EducationRecord[] = [
  {
    id: 'edu-1',
    degree: 'Ph.D. in Computer Science & Engineering',
    level: 'Doctoral Research',
    institution: 'Biju Patnaik University of Technology (BPUT, Odisha)',
    period: '2023 - Present',
    grade: 'Coursework Completed (9.20 CGPA)',
    specialization: 'Algorithmic Optimization in Edge Computing & Distributed Graph AI',
    status: 'In Progress',
    details: 'Doctoral advisor: Dr. S. K. Mahapatra. Published 2 IEEE conference papers and 1 Q1 journal article.'
  },
  {
    id: 'edu-2',
    degree: 'M.Tech in Computer Science & Engineering',
    level: "Master's Degree",
    institution: 'Indian Institute of Technology Kharagpur (IIT-KGP)',
    period: '2014 - 2016',
    grade: '9.42 / 10.0 CGPA (Institute Gold Medalist)',
    specialization: 'Distributed Systems & Machine Learning',
    status: 'Completed',
    details: 'Master thesis: Fault-tolerant consensus protocols for high-throughput distributed databases. Sponsored by MHRD scholarship.'
  },
  {
    id: 'edu-3',
    degree: 'B.Tech in Computer Science & Engineering',
    level: "Bachelor's Degree",
    institution: 'Raajdhani Engineering College (Autonomous), Bhubaneswar',
    period: '2006 - 2010',
    grade: '8.85 CGPA (First Class with Distinction Honours)',
    specialization: 'Computer Science & Software Systems',
    status: 'Completed',
    details: 'Best Capstone Project Award for Automated Campus Attendance System using biometric edge modules.'
  }
];

export const INITIAL_RESOURCES: LearningResource[] = [
  {
    id: 'res-1',
    title: 'Unit 3 Dynamic Programming: Memoization & Tabulation Master Handout',
    course: 'CS-401 Design & Analysis of Algorithms',
    batch: 'B.Tech CSE - 5th Sem (Sec A & B)',
    unit: 'Unit 3: Dynamic Programming',
    category: 'NOTE',
    url: '#',
    fileType: 'PDF',
    fileSize: '3.8 MB',
    downloadsCount: 142,
    viewsCount: 285,
    dateAdded: '02 Oct 2026',
    description: 'Comprehensive handwritten & typed lecture notes covering Matrix Chain Multiplication, Longest Common Subsequence, and 0/1 Knapsack with recurrence proofs.'
  },
  {
    id: 'res-2',
    title: 'Unit 2 Greedy Algorithms & Minimum Spanning Trees (Kruskal with DSU)',
    course: 'CS-401 Design & Analysis of Algorithms',
    batch: 'B.Tech CSE - 5th Sem (Sec A)',
    unit: 'Unit 2: Greedy & Graph Strategies',
    category: 'NOTE',
    url: '#',
    fileType: 'PDF',
    fileSize: '2.4 MB',
    downloadsCount: 198,
    viewsCount: 340,
    dateAdded: '24 Sep 2026',
    description: 'Detailed analysis of Greedy Choice property, Cut property in MSTs, and step-by-step Disjoint Set Union (DSU) rank and path compression proofs.'
  },
  {
    id: 'res-3',
    title: 'Lab Manual Sheet 4: Kruskal & Prim Algorithm Implementation in C++ STL',
    course: 'CS-401L Algorithms Lab',
    batch: 'B.Tech CSE - 5th Sem (Sec A & B)',
    unit: 'Lab Module 4',
    category: 'NOTE',
    url: '#',
    fileType: 'PDF',
    fileSize: '1.5 MB',
    downloadsCount: 68,
    viewsCount: 94,
    dateAdded: '28 Sep 2026',
    description: 'Hands-on lab problem set, test cases, and edge inputs for graph algorithms lab evaluation.'
  },
  {
    id: 'res-4',
    title: 'Recorded Lecture 14: Dynamic Programming - Matrix Chain Multiplication Recurrence',
    course: 'CS-401 Design & Analysis of Algorithms',
    batch: 'B.Tech CSE - 5th Sem (Sec A)',
    unit: 'Unit 3: Dynamic Programming',
    category: 'VIDEO',
    url: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600',
    duration: '52 mins',
    fileType: 'MP4',
    platform: 'Local',
    viewsCount: 124,
    dateAdded: '03 Oct 2026',
    description: 'Classroom recording from Academic Block 2, Room 304. Deep dive into optimal substructure, split index k, and building m[i,j] table.'
  },
  {
    id: 'res-5',
    title: 'Recorded Lecture 11: Single Source Shortest Paths - Dijkstra Algorithm with Min-Heap',
    course: 'CS-401 Design & Analysis of Algorithms',
    batch: 'B.Tech CSE - 5th Sem (Sec A & B)',
    unit: 'Unit 2: Graph Algorithms',
    category: 'VIDEO',
    url: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600',
    duration: '48 mins',
    fileType: 'MP4',
    platform: 'Local',
    viewsCount: 168,
    dateAdded: '20 Sep 2026',
    description: 'Live whiteboard lecture explaining why Dijkstra fails on negative weight edges and how priority queue achieves O((V+E)log V).'
  },
  {
    id: 'res-6',
    title: 'NPTEL Official Video: Advanced Dynamic Programming & Bellman Equations',
    course: 'CS-401 Design & Analysis of Algorithms',
    batch: 'B.Tech CSE - 5th Sem',
    unit: 'Unit 3: Dynamic Programming',
    category: 'VIDEO_LINK',
    url: 'https://www.youtube.com/watch?v=OQ5jsbhAv_M',
    thumbnail: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=600',
    duration: '58 mins',
    platform: 'NPTEL',
    viewsCount: 310,
    dateAdded: '15 Sep 2026',
    description: 'Prof. Naveen Garg, IIT Delhi official NPTEL video session on optimal substructure and subproblem graphs.'
  },
  {
    id: 'res-7',
    title: 'MIT 6.006 Lecture: Introduction to Graph Algorithms, BFS and DFS Traversal',
    course: 'CS-401 Design & Analysis of Algorithms',
    batch: 'B.Tech CSE - 5th Sem',
    unit: 'Unit 2: Graph Algorithms',
    category: 'VIDEO_LINK',
    url: 'https://www.youtube.com/watch?v=s-CYnVz-uh4',
    thumbnail: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600',
    duration: '50 mins',
    platform: 'YouTube',
    viewsCount: 245,
    dateAdded: '10 Sep 2026',
    description: 'MIT OpenCourseWare official lecture by Prof. Erik Demaine. Recommended for conceptual clarity on edge classification.'
  },
  {
    id: 'res-8',
    title: 'Google Drive Recording: Lab Doubts Session on Disjoint Set Union (DSU)',
    course: 'CS-401L Algorithms Lab',
    batch: 'B.Tech CSE - 5th Sem (Sec A & B)',
    unit: 'Lab Module 4',
    category: 'VIDEO_LINK',
    url: 'https://drive.google.com/file/d/rec-dsu-lab-recording',
    thumbnail: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=600',
    duration: '35 mins',
    platform: 'Google Drive',
    viewsCount: 89,
    dateAdded: '29 Sep 2026',
    description: 'Online Google Meet recording explaining union by rank and path compression logic with step-by-step code walkthrough.'
  },
  {
    id: 'res-9',
    title: 'Visualgo: Interactive Data Structure & Algorithm Animation Sandbox',
    course: 'CS-401 Design & Analysis of Algorithms',
    batch: 'B.Tech CSE - 5th Sem',
    category: 'WEBSITE_LINK',
    platform: 'Website',
    websiteName: 'Visualgo.net',
    url: 'https://visualgo.net/en',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600',
    viewsCount: 412,
    dateAdded: '01 Sep 2026',
    description: 'Interactive visual animations of sorting, graph traversals, Dijkstra, Prim, Kruskal, and dynamic programming tables created by Dr. Steven Halim.'
  },
  {
    id: 'res-10',
    title: 'GeeksforGeeks: Matrix Chain Multiplication (DP-8) Guide & Code',
    course: 'CS-401 Design & Analysis of Algorithms',
    batch: 'B.Tech CSE - 5th Sem',
    category: 'WEBSITE_LINK',
    platform: 'Website',
    websiteName: 'GeeksforGeeks',
    url: 'https://www.geeksforgeeks.org/matrix-chain-multiplication-dp-8/',
    thumbnail: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=600',
    viewsCount: 350,
    dateAdded: '03 Oct 2026',
    description: 'Detailed tutorial with recursion tree, memoized solution, and space-optimized tabular approach with test cases in C++, Java, and Python.'
  },
  {
    id: 'res-11',
    title: 'LeetCode Curated Dynamic Programming Problem Set for Campus Placement',
    course: 'CS-401 Design & Analysis of Algorithms',
    batch: 'B.Tech CSE - 5th Sem',
    category: 'WEBSITE_LINK',
    platform: 'Website',
    websiteName: 'LeetCode',
    url: 'https://leetcode.com/tag/dynamic-programming/',
    thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600',
    viewsCount: 520,
    dateAdded: '05 Sep 2026',
    description: 'High-frequency coding problems asked in top tech company on-campus recruitment and technical interviews.'
  },
  {
    id: 'res-12',
    title: 'REC Autonomous GitHub Repository: CSE Algorithms Starter Code & Test Suites',
    course: 'CS-401L Algorithms Lab',
    batch: 'B.Tech CSE - 5th Sem',
    category: 'WEBSITE_LINK',
    platform: 'Website',
    websiteName: 'GitHub',
    url: 'https://github.com/rec-cse-algorithms',
    thumbnail: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=600',
    viewsCount: 290,
    dateAdded: '15 Sep 2026',
    description: 'Official department GitHub organization containing starter templates, makefiles, unit tests, and reference benchmarking scripts.'
  }
];


